extends "res://ActionAnimationManager.gd"


const JUMP_SPRITE_ANIME_ID = 0
const WALK_FORWARD_SPRITE_ANIME_ID = 1
const GROUND_IDLE_SPRITE_ANIME_ID = 2
const AIR_IDLE_SPRITE_ANIME_ID = 3
const NEUTRAL_MELEE_SPRITE_ANIME_ID = 4

const NEUTRAL_SPECIAL_SPRITE_ANIME_ID = 6
const REBOUND_SPRITE_ANIME_ID = 7
const CROUCH_SPRITE_ANIME_ID = 8
const NEUTRAL_TOOL_SPRITE_ANIME_ID = 9
const AUTO_RIPOST_SPRITE_ANIME_ID = 10
const AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID = 11
const AIR_DASH_SPRITE_ANIME_ID = 12
const RIPOST_SPRITE_ANIME_ID = 13
const NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID = 14
const AIR_MOVE_SPRITE_ANIME_ID = 15
const AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID = 16
const AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID = 17
const BACK_SPECIAL_SPRITE_ANIME_ID = 18
const LANDING_LAG_SPRITE_ANIME_ID = 19
const WALK_BACKWARD_SPRITE_ANIME_ID = 20
const DOWN_WARD_MELEE_SPRITE_ANIME_ID = 21
const FORWARD_SPECIAL_SPRITE_ANIME_ID = 22
const UPWARD_TOOL_SPRITE_ANIME_ID = 23
const LANDING_HITSTUN_SPRITE_ANIME_ID = 24
const INVULNERABLE_HITSTUN_AIR_SPRITE_ANIME_ID = 25
const BACKWARD_TOOL_SPRITE_ANIME_ID = 26
const FORWARD_MELEE_SPRITE_ANIME_ID = 27
const GROUND_FORWARD_DASH_SPRITE_ANIME_ID = 28
const GROUND_BACKWARD_DASH_SPRITE_ANIME_ID = 29
const GROUND_GRAB_SPRITE_ANIME_ID = 30
const UPWARD_SPECIAL_SPRITE_ANIME_ID = 31
const DOWNWARD_SPECIAL_SPRITE_ANIME_ID = 32
const GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID = 33
const FORWARD_ROLLING_TECH_SPRITE_ANIME_ID = 34
const BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID = 35
const CEILING_TECH_SPRITE_ANIME_ID = 36
const WALL_TECH_SPRITE_ANIME_ID = 37
const UPWARD_MELEE_SPRITE_ANIME_ID = 38
const FORWARD_TOOL_SPRITE_ANIME_ID = 39
const DOWNWARD_TOOL_SPRITE_ANIME_ID = 40
const BACKWARD_MELEE_SPRITE_ANIME_ID = 41
const AIR_HITSTUN_SPRITE_ANIME_ID = 42
const BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID = 43
const PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID = 44
const CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID = 45
const PLATFORM_DROP_SPRITE_ANIME_ID = 46
const UNCROUCH_SPRITE_ANIME_ID = 47
const ON_HIT_GROUND_GRAB_SPRITE_ANIME_ID = 48
const GROUND_DASH_CANCEL_RECOVERY_SPRITE_ANIME_ID = 49
const PUSH_BLOCK_SPRITE_ANIME_ID = 50
const GROUND_GRAB_THROW_SPRITE_ANIME_ID = 51
const AIR_GRAB_THROW_SPRITE_ANIME_ID = GROUND_GRAB_THROW_SPRITE_ANIME_ID #same for now
const AIR_GRAB_SPRITE_ANIME_ID = 52
const ON_HIT_AIR_GRAB_SPRITE_ANIME_ID = 53
const NON_CROUCH_CANCELABLED_F_GROUND_DASH_SPRITE_ANIME_ID=54
const NON_CROUCH_CANCELABLED_B_GROUND_DASH_SPRITE_ANIME_ID=55
const PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID=56
const PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_SPRITE_ANIME_ID=57
const STUNNED_SPRITE_ANIME_ID=58
const AIR_JUMP_SPRITE_ANIME_ID=59
const BACK_AIR_DASH_SPRITE_ANIME_ID=60
const ON_HIT_BACK_TOOL_SPRITE_ANIME_ID=61
const NEUTRAL_TOOL_COUNTER_HIT_SPRITE_ANIME_ID=62
const UP_TOOL_REKA_SPRITE_ANIME_ID=63
const UP_TOOL_ON_HIT_SPRITE_ANIME_ID = 64
const UP_TOOL_REKA_ON_HIT_SPRITE_ANIME_ID = 65
const ANGRY_D_TOOL_SPRITE_ANIME_ID = 66
const ANGRY_B_SPECIAL_SPRITE_ANIME_ID = 67
const ANGRY_D_SPECIAL_SPRITE_ANIME_ID = 68
const ANGRY_N_SPECIAL_SPRITE_ANIME_ID = 69
const EXPIRED_AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID=70
const BASIC_CROUCH_CANCEL_SPRITE_ANIME_ID=71
const NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID=72
const INVULNERABLE_GUARD_BREAK_SPRITE_ANIME_ID=73
const ANGRY_U_SPECIAL_SPRITE_ANIME_ID = 74
const ANGRY_F_SPECIAL_SPRITE_ANIME_ID = 75
const ANGRY_AIR_SPECIAL_SPRITE_ANIME_ID = 76
const FORWARD_TOOL_REKA_SPRITE_ANIME_ID = 77
const FORWARD_TOOL_REKA_ON_HIT_SPRITE_ANIME_ID = 78


const GROUND_GRAB_FORWARD_THROW_SPRITE_ANIME_ID=79
const GROUND_GRAB_FORWARD_DOWN_THROW_SPRITE_ANIME_ID=80
const GROUND_GRAB_DOWN_THROW_SPRITE_ANIME_ID=81
const GROUND_GRAB_BACKWARD_DOWN_THROW_SPRITE_ANIME_ID=82
const GROUND_GRAB_BACKWARD_THROW_SPRITE_ANIME_ID=83
const GROUND_GRAB_BACKWARD_UP_THROW_SPRITE_ANIME_ID=84
const GROUND_GRAB_UP_THROW_SPRITE_ANIME_ID=85
const GROUND_GRAB_FORWARD_UP_THROW_SPRITE_ANIME_ID=86


#Movement animation ids
const JUMP_MVM_ANIME_ID = 0
const AIR_MOVE_FORWARD_MVM_ANIME_ID = 1
const GROUND_MOVE_FORWARD_MVM_ANIME_ID = 2
const GROUND_MOVE_BACKWARD_MVM_ANIME_ID = 3
const AIR_MOVE_BACKWARD_MVM_ANIME_ID = 4
const AIR_IDLE_MVM_ANIME_ID = 5
const AIR_DASH_FORWARD_MVM_ANIME_ID = 6
const AIR_DASH_BACKWARD_MVM_ANIME_ID = 7
const GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID = 8
const NEUTRAL_MELEE_MVM_ANIME_ID = 9
const NEUTRAL_SPECIAL_MVM_ANIME_ID = 10
const REBOUND_MVM_ANIME_ID = 11
const JUMP_FORWARD_MVM_ANIME_ID = 12
const JUMP_BACKWARD_MVM_ANIME_ID = 13
const AIR_DASH_DOWNWARD_MVM_ANIME_ID = 14
const RIPOST_MVM_ANIME_ID = 15
const AIR_MOVE_STOP_MVM_ANIME_ID = 16
const BACK_SPECIAL_MVM_ANIME_ID = 17
const FORWARD_SPECIAL_MVM_ANIME_ID = 18
const WALL_BOUNCE_MVM_ANIME_ID = 19
const INVULNERABLE_HITSTUN_AIR_MVM_ANIME_ID = 20
const BACKWARD_TOOL_MVM_ANIME_ID = 21
const FORWARD_MELEE_MVM_ANIME_ID = 22
const GROUND_FORWARD_DASH_MVM_ANIME_ID = 23
const GROUND_BACKWARD_DASH_MVM_ANIME_ID = 24
const CEILING_TECH_MVM_ANIME_ID = 25
const WALL_TECH_MVM_ANIME_ID = 26
const GROUND_IN_PLACE_TECH_MVM_ANIME_ID = 27
const FORWARD_TOOL_MVM_ANIME_ID = 28
const BACKWARD_MELEE_MVM_ANIME_ID = 29
const LEAVE_PLATFROM_HALT_MVM_ANIME_ID = 30
const LAND_ON_PLATFROM_MVM_ANIME_ID = 31
const AIR_HITSTUN_BREAK_FREE_MVM_ANIME_ID = 32
const TECH_ROLL_BACKWARD_MVM_ANIME_ID = 33
const TECH_ROLL_FORWARD_MVM_ANIME_ID = 34
const STOP_PLATFORM_LEAVE_MOMENTUM_MVM_ANIME_ID  = 35
const PLATFORM_DROP_MVM_ANIME_ID  = 36
const GROUND_GRAB_MVM_ANIME_ID = 37
const ON_HIT_GROUND_GRAB_MVM_ANIME_ID = 38
const AIR_BLOCK_STUN_MVM_ANIME_ID = 39
const PUSH_BLOCK_MVM_ANIME_ID = 40
const GROUND_GRAB_UP_THROW_MVM_ANIME_ID = 41
const GROUND_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID = 42
const GROUND_GRAB_FORWARD_THROW_MVM_ANIME_ID = 43
const GROUND_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID = 44
const GROUND_GRAB_DOWN_THROW_MVM_ANIME_ID = 45
const GROUND_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID = 46
const GROUND_GRAB_BACKWARD_THROW_MVM_ANIME_ID = 47
const GROUND_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID = 48
const AIR_GRAB_UP_THROW_MVM_ANIME_ID = 49
const AIR_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID = 50
const AIR_GRAB_FORWARD_THROW_MVM_ANIME_ID = 51
const AIR_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID = 52
const AIR_GRAB_DOWN_THROW_MVM_ANIME_ID = 53
const AIR_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID = 54
const AIR_GRAB_BACKWARD_THROW_MVM_ANIME_ID = 55
const AIR_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID = 56
const AIR_GRAB_MVM_ANIME_ID = 57
const ON_HIT_AIR_GRAB_MVM_ANIME_ID = 58
const ZERO_AIR_MVM_ANIME_ID = 59
const STUNNED_MVM_ANIME_ID = 60
const PERFECT_MVM_ANIME_ID = 61
const REBOUND_CLASH_BREAK_MVM_ANIME_ID = 62
const NON_MVM_PUSH_BLOCKING_MVM_ANIME_ID = 63
const UP_MELEE_MVM_ANIME_ID = 64
const ON_HIT_BACK_TOOL_MVM_ANIME_ID = 65
const AIR_TOOL_MVM_ANIME_ID = 66
const ANGRY_B_SPECIAL_MVM_ANIME_ID = 67
const ANGRY_F_SPECIAL_MVM_ANIME_ID = 68
const MOMENTUM_STOP_MVM_ANIME_ID = 69
const CORNER_HITTING_PUSH_AWAY_MVM_ANIME_ID = 70
const GROUND_TECH_BOUNCE_UP_MVM_ANIME_ID = 71
const WALL_TECH_BOUNCE_UP_MVM_ANIME_ID = 72
const WALL_TECH_BOUNCE_DOWN_MVM_ANIME_ID = 73
const CEILING_BOUNCE_BACK_TECH_MVM_ANIME_ID =74
const CEILING_BOUNCE_FORWARD_TECH_MVM_ANIME_ID = 75
const AIR_TECH_IN_PLACE_MVM_ANIME_ID = 76
const REBOUND_CLASH_BREAK_VICTIM_MVM_ANIME_ID = 77
const F_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID = 78
const B_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID = 79
const BREAK_FROM_HITSTUN_HALT_MVM_ANIME_ID = 80
const OKI_MOMENTUM_STOP_MVM_ANIME_ID = 81
const PROXIMITY_GUARD_STOP_MVM_ANIME_ID = 82
const FORWARD_SPECIAL_STOP_MVM_ANIME_ID = 83
const LANDING_LAG_MVM_ANIME_ID = 84
const INVULNERABLE_GUARD_BREAK_MVM_ANIME_ID = 85
const GRAB_CANCEL_MOMENTUM_STOP_MVM_ANIME_ID = 86
#const TEST_CIRCULAR_MOVE_MVM_ANIME_ID = 87
const ANGRY_U_SPECIAL_MVM_ANIME_ID = 87
const AIR_KEEP_MOMENTUM_MVM_ANIME_ID =88
const ANGRY_AIR_SPECIAL_MVM_ANIME_ID =89
const GROUND_GRAB_NEUTRAL_THROW_MVM_ANIME_ID=90
const AIR_GRAB_NEUTRAL_THROW_MVM_ANIME_ID = 91
const GETTING_PUSH_BLOCKED_IN_NEUTRAL_MVM_ANIME_ID=92
#action  animation ids
const JUMP_ACTION_ID = 0
const AIR_MOVE_FORWARD_ACTION_ID = 1
const GROUND_MOVE_FORWARD_ACTION_ID = 2
const GROUND_MOVE_BACKWARD_ACTION_ID = 3
const AIR_MOVE_BACKWARD_ACTION_ID = 4
const AIR_IDLE_ACTION_ID = 5
const AIR_DASH_FORWARD_ACTION_ID = 6
const AIR_DASH_BACKWARD_ACTION_ID = 7
const GROUND_IDLE_ACTION_ID = 8
const NEUTRAL_MELEE_ACTION_ID = 9
const FORWARD_MELEE_ACTION_ID = 39
const BACKWARD_MELEE_ACTION_ID = 53
const DOWNWARD_MELEE_ACTION_ID = 32
const UPWARD_MELEE_ACTION_ID = 50
const NEUTRAL_SPECIAL_ACTION_ID = 10
const FORWARD_SPECIAL_ACTION_ID = 33 
const BACKWARD_SPECIAL_ACTION_ID = 27 
const DOWNWARD_SPECIAL_ACTION_ID = 44
const UPWARD_SPECIAL_ACTION_ID = 65
const REBOUND_ACTION_ID = 11
const CROUCH_ACTION_ID = 12
const AIR_NEUTRAL_MELEE_ACTION_ID = 13
const AIR_NEUTRAL_SPECIAL_ACTION_ID = 14
const JUMP_FORWARD_ACTION_ID = 15
const JUMP_BACKWARD_ACTION_ID = 16
const AIR_DASH_DOWNWARD_ACTION_ID = 17
const AIR_NEUTRAL_TOOL_ACTION_ID = 18
const NEUTRAL_TOOL_ACTION_ID = 19
const FORWARD_TOOL_ACTION_ID = 51 
const BACKWARD_TOOL_ACTION_ID = 38
const DOWNWARD_TOOL_ACTION_ID = 52
const UPWARD_TOOL_ACTION_ID = 34 

const PAUSE_PLAYER_ACTION_ID = 21
const GROUND_RIPOST_ACTION_ID = 22
const AIR_RIPOST_ACTION_ID = 23
const AUTO_RIPOST_ACTION_ID = 24#AUTO RIPOST
const AUTO_RIPOST_ON_HIT_ACTION_ID = 25#AUTORIPOST ON HIT
const AIR_MOVE_STOP_ACTION_ID = 26
#const BACKWARD_SPECIAL_ACTION_ID = 27
const AIR_AUTO_RIPOST_ACTION_ID = 28
const AIR_AUTO_RIPOST_ON_HIT_ACTION_ID = 29
const LANDING_STOP_MOMENTUM_ACTION_ID = 30
const LANDING_LAG_ACTION_ID = 31

const WALL_BOUNCE_ACTION_ID = 36

const GROUND_FORWARD_DASH_ACTION_ID = 40
const GROUND_BACKWARD_DASH_ACTION_ID = 41
const GROUND_GRAB_ACTION_ID = 42 #anti-block
const AIR_GRAB_ACTION_ID = 43 #AIR anti-block

const GROUND_IN_PLACE_TECH_ACTION_ID = 45
const ROLLING_FORWARD_TECH_ACTION_ID = 46
const ROLLING_BACKWARD_TECH_ACTION_ID = 47
const CEILING_TECH_ACTION_ID = 48
const WALL_TECH_ACTION_ID = 49

const BUDGET_BLOCK_HIT_LAG_ACTION_ID = 55
const PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID = 56
const CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID = 57
const LEAVE_PLATFROM_HALT_ACTION_ID = 58
const LAND_ON_PLATFROM_ACTION_ID=59
const AIR_HITSTUN_BREAK_FREE_ACTION_ID = 60
const STOP_PLATFORM_LEAVE_MOMENTUM_ACTION_ID = 61
const PLATFORM_DROP_ACTION_ID = 62
const PLATFORM_ANIMATION_CANCEL_ACTION_ID = 63
const UNCROUCH_ACTION_ID = 64
const ON_HIT_GROUND_GRAB_ACTION_ID = 66
const FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID = 67
const AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID = 68
const GETTING_PUSH_BLOCKED_ACTION_ID = 69
const GROUND_PUSH_BLOCKING_ACTION_ID = 70

const GROUND_GRAB_UP_THROW_ACTION_ID = 71
const GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID = 72
const GROUND_GRAB_FORWARD_THROW_ACTION_ID = 73
const GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID = 74
const GROUND_GRAB_DOWN_THROW_ACTION_ID = 75
const GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID = 76
const GROUND_GRAB_BACKWARD_THROW_ACTION_ID = 77
const GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID = 78

const ON_HIT_AIR_GRAB_ACTION_ID = 79


const AIR_GRAB_UP_THROW_ACTION_ID = 80
const AIR_GRAB_FORWARD_UP_THROW_ACTION_ID = 81
const AIR_GRAB_FORWARD_THROW_ACTION_ID = 82
const AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID = 83
const AIR_GRAB_DOWN_THROW_ACTION_ID = 84
const AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID = 85
const AIR_GRAB_BACKWARD_THROW_ACTION_ID = 86
const AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID = 87
const APEX_ONLY_FAST_FALL_ACTION_ID = 88
const NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID = 89
const NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID = 90

const PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID=91
const PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID=92
const STUNNED_ACTION_ID=93
const PERFECT_MOMENTUM_STOP_BLOCK_ACTION_ID=94
const REBOUND_CLASH_BREAK_ACTION_ID=95
const AIR_PUSH_BLOCKING_ACTION_ID = 96
const AIR_JUMP_ACTION_ID = 97
const AIR_JUMP_FORWARD_ACTION_ID = 98
const AIR_JUMP_BACKWARD_ACTION_ID = 99
const ON_HIT_BACK_TOOL_ACTION_ID = 100
const NEUTRAL_TOOL_COUNTER_HIT_ACTION_ID = 101
const UP_TOOL_NORMAL_ACTION_ID=102
const UP_TOOL_REKA_ACTION_ID=103
const UP_TOOL_ON_HIT_ACTION_ID=104
const UP_TOOL_REKA_ON_HIT_ACTION_ID=105
const ANGRY_D_TOOL_ACTION_ID=106
const ANGRY_B_SPECIAL_ACTION_ID=107
const ANGRY_D_SPECIAL_ACTION_ID=108
const ANGRY_F_SPECIAL_ACTION_ID= 109
const ANGRY_N_SPECIAL_ACTION_ID= 110
const ON_HIT_F_SPECIAL_MOMENTUM_STOP_ACTION_ID= 111
const MOMENTUM_STOP_ACTION_ID=112
const CORNER_HITTING_PUSH_AWAY_ACTION_ID = 113
const GROUND_BOUNCE_UP_TECH_ACTION_ID = 114
	

const WALL_BOUNCE_UP_TECH_ACTION_ID=115
const WALL_BOUNCE_DOWN_TECH_ACTION_ID=116
const WALL_BOUNCE_AWAY_TECH_ACTION_ID=117
	
const CEILING_BOUNCE_DOWN_TECH_ACTION_ID=118
const CEILING_BOUNCE_FORWARD_TECH_ACTION_ID=119
const CEILING_BOUNCE_BACK_TECH_ACTION_ID=120
const REBOUND_CLASH_BREAK_VICTIM_ACTION_ID=121
const BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID=122
const BASIC_CROUCH_CANCEL_ACTION_ID=123
const BREAK_FROM_HITSTUN_HALT_ACTION_ID=124
const NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID=125
const NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID=126
const NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID=127
const SLIDING_GROUND_IDLE_ACTION_ID = 128
const FORWARD_SPECIAL_ON_HIT_STOP_ACTION_ID = 129
const INVULNERABLE_GUARD_BREAK_ACTION_ID = 130
const GRAB_CANCEL_MOMENTUM_STOP_ACTION_ID = 131
const ANGRY_U_SPECIAL_ACTION_ID = 132
const SLIDING_AIR_IDLE_ACTION_ID = 133
const ANGRY_AIR_SPECIAL_ACTION_ID = 134
const FORWARD_TOOL_REKA_ACTION_ID = 135
const FORWARD_TOOL_NORMAL_ACTION_ID = 136
const FORWARD_TOOL_REKA_ON_HITACTION_ID = 137
const GROUND_GRAB_NEUTRAL_THROW_ACTION_ID=138
const AIR_GRAB_NEUTRAL_THROW_ACTION_ID = 139
const GETTING_PUSH_BLOCKED_IN_NEUTRAL_ACTION_ID = 140
const LARGEST_ACTION_ID = 140


const CALM_ANIMATIONS_IX = 0
const ANGRY_ANIMATIONS_IX = 1


var currentActionIdGroup = CALM_ANIMATIONS_IX

var actionIdGroups = []

#map that has sprite ids that when hit, lose angry (angry specials)
var onHitLoseAngryAnimes={}
func _ready():
	LANDING_HITSTUN_ACTION_ID = 35
	INVULNERABLE_AIR_HITSTUN_ACTION_ID = 37
	AIR_HITSTUN_ACTION_ID=54
	attackMaps[MELEE_IX][NEUTRAL_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][DOWN_WARD_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][FORWARD_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][BACKWARD_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][UPWARD_MELEE_SPRITE_ANIME_ID] = true
	
	attackMaps[SPECIAL_IX][NEUTRAL_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][BACK_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][FORWARD_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][EXPIRED_AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][DOWNWARD_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][UPWARD_SPECIAL_SPRITE_ANIME_ID] = true 
	attackMaps[SPECIAL_IX][ANGRY_B_SPECIAL_SPRITE_ANIME_ID] = true 
	attackMaps[SPECIAL_IX][ANGRY_AIR_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][ANGRY_D_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][ANGRY_U_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][ANGRY_N_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][ANGRY_F_SPECIAL_SPRITE_ANIME_ID] = true

	
	attackMaps[TOOL_IX][NEUTRAL_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][UPWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][BACKWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][FORWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][DOWNWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NEUTRAL_TOOL_COUNTER_HIT_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][UP_TOOL_REKA_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][ON_HIT_BACK_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][FORWARD_TOOL_REKA_SPRITE_ANIME_ID] = true
	
	
	#the special effects attack type map is same as attack map in belt's case
	visualSFXAttackMap=attackMaps
	
	audioSFXAttackMap = [{},{},{}]
	
	for k1 in [MELEE_IX,SPECIAL_IX,TOOL_IX]:
		var map = attackMaps[k1]
		for k2 in map.keys():
			audioSFXAttackMap[k1][k2]=map[k2]
	
	#angry hits have special hit sfx, so remove from the audio index
	audioSFXAttackMap[SPECIAL_IX].erase(ANGRY_B_SPECIAL_SPRITE_ANIME_ID)
	audioSFXAttackMap[SPECIAL_IX].erase(ANGRY_AIR_SPECIAL_SPRITE_ANIME_ID)
	audioSFXAttackMap[SPECIAL_IX].erase(ANGRY_D_SPECIAL_SPRITE_ANIME_ID)
	audioSFXAttackMap[SPECIAL_IX].erase(ANGRY_U_SPECIAL_SPRITE_ANIME_ID)
	audioSFXAttackMap[SPECIAL_IX].erase(ANGRY_N_SPECIAL_SPRITE_ANIME_ID)
	audioSFXAttackMap[SPECIAL_IX].erase(ANGRY_F_SPECIAL_SPRITE_ANIME_ID)

	
	
	
	
	animationLookup[SPRITE_ANIME_IX][JUMP_ACTION_ID]=JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_JUMP_ACTION_ID]=AIR_JUMP_SPRITE_ANIME_ID	
	#animationLookup[SPRITE_ANIME_IX][AIR_MOVE_FORWARD_ACTION_ID]=AIR_MOVE_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][AIR_MOVE_BACKWARD_ACTION_ID]=AIR_MOVE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_MOVE_FORWARD_ACTION_ID]=null
	animationLookup[SPRITE_ANIME_IX][AIR_MOVE_BACKWARD_ACTION_ID]=null
	animationLookup[SPRITE_ANIME_IX][AIR_IDLE_ACTION_ID]=AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_MOVE_FORWARD_ACTION_ID]=WALK_FORWARD_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_MOVE_BACKWARD_ACTION_ID]=WALK_BACKWARD_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_IDLE_ACTION_ID]=GROUND_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][SLIDING_GROUND_IDLE_ACTION_ID]=GROUND_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][SLIDING_AIR_IDLE_ACTION_ID]=AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_DASH_FORWARD_ACTION_ID]=AIR_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_DASH_BACKWARD_ACTION_ID]=BACK_AIR_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_MELEE_ACTION_ID]=NEUTRAL_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_MELEE_ACTION_ID]=NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_SPECIAL_ACTION_ID]=NEUTRAL_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_SPECIAL_ACTION_ID]=AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][REBOUND_ACTION_ID]=REBOUND_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][REBOUND_CLASH_BREAK_VICTIM_ACTION_ID]=REBOUND_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][CROUCH_ACTION_ID]=CROUCH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][JUMP_FORWARD_ACTION_ID]=JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][JUMP_BACKWARD_ACTION_ID]=JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_JUMP_FORWARD_ACTION_ID]=AIR_JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_JUMP_BACKWARD_ACTION_ID]=AIR_JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_DASH_DOWNWARD_ACTION_ID]=null
	animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_TOOL_ACTION_ID]=AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_TOOL_ACTION_ID]=NEUTRAL_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_RIPOST_ACTION_ID]=RIPOST_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][GROUND_RIPOST_ACTION_ID]=RIPOST_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AUTO_RIPOST_ACTION_ID]=AUTO_RIPOST_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_AUTO_RIPOST_ACTION_ID]=AUTO_RIPOST_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AUTO_RIPOST_ON_HIT_ACTION_ID]=AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_AUTO_RIPOST_ON_HIT_ACTION_ID]=AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][HITSTUN_ACTION_ID] = HITSTUN_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][AIR_MOVE_STOP_ACTION_ID] = AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_MOVE_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][BACKWARD_SPECIAL_ACTION_ID] = BACK_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][LANDING_STOP_MOMENTUM_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][LANDING_LAG_ACTION_ID] = LANDING_LAG_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][DOWNWARD_MELEE_ACTION_ID] = DOWN_WARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_SPECIAL_ACTION_ID] = FORWARD_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UPWARD_TOOL_ACTION_ID] = UPWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][LANDING_HITSTUN_ACTION_ID] = LANDING_HITSTUN_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][INVULNERABLE_AIR_HITSTUN_ACTION_ID] = INVULNERABLE_HITSTUN_AIR_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BACKWARD_TOOL_ACTION_ID] = BACKWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_MELEE_ACTION_ID] = FORWARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_FORWARD_DASH_ACTION_ID] = GROUND_FORWARD_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_BACKWARD_DASH_ACTION_ID] = GROUND_BACKWARD_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_ACTION_ID] = GROUND_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_ACTION_ID] = AIR_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][DOWNWARD_SPECIAL_ACTION_ID] = DOWNWARD_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UPWARD_SPECIAL_ACTION_ID] = UPWARD_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_IN_PLACE_TECH_ACTION_ID] = GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_BOUNCE_UP_TECH_ACTION_ID] = GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ROLLING_BACKWARD_TECH_ACTION_ID] = BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ROLLING_FORWARD_TECH_ACTION_ID] = FORWARD_ROLLING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_BOUNCE_BACK_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_BOUNCE_FORWARD_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_BOUNCE_DOWN_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_UP_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_DOWN_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_AWAY_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UPWARD_MELEE_ACTION_ID] = UPWARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_TOOL_ACTION_ID] = FORWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][DOWNWARD_TOOL_ACTION_ID] = DOWNWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BACKWARD_MELEE_ACTION_ID] = BACKWARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_HITSTUN_ACTION_ID] = AIR_HITSTUN_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BUDGET_BLOCK_HIT_LAG_ACTION_ID] = BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][LEAVE_PLATFROM_HALT_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][LAND_ON_PLATFROM_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][AIR_HITSTUN_BREAK_FREE_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][STOP_PLATFORM_LEAVE_MOMENTUM_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][PLATFORM_DROP_ACTION_ID] = PLATFORM_DROP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PLATFORM_ANIMATION_CANCEL_ACTION_ID] = AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UNCROUCH_ACTION_ID] = UNCROUCH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ON_HIT_GROUND_GRAB_ACTION_ID] = ON_HIT_GROUND_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ON_HIT_AIR_GRAB_ACTION_ID] = ON_HIT_AIR_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = GROUND_DASH_CANCEL_RECOVERY_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = GROUND_DASH_CANCEL_RECOVERY_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][GETTING_PUSH_BLOCKED_ACTION_ID] = PUSH_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GETTING_PUSH_BLOCKED_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][GROUND_PUSH_BLOCKING_ACTION_ID] = PUSH_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_PUSH_BLOCKING_ACTION_ID] = PUSH_BLOCK_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_DOWN_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_DOWN_THROW_ACTION_ID] = GROUND_GRAB_DOWN_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_DOWN_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_UP_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_UP_THROW_ACTION_ID] = GROUND_GRAB_UP_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_UP_THROW_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_NEUTRAL_THROW_ACTION_ID] = GROUND_GRAB_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_UP_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_UP_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_FORWARD_UP_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_FORWARD_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_DOWN_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_DOWN_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_BACKWARD_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID] 	
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_NEUTRAL_THROW_ACTION_ID] = AIR_GRAB_THROW_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID] = NON_CROUCH_CANCELABLED_F_GROUND_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID] = NON_CROUCH_CANCELABLED_B_GROUND_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][APEX_ONLY_FAST_FALL_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][DELAYED_N_MELEE_1_ACTION_ID] = NEUTRAL_MELEE_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][DELAYED_N_MELEE_2_ACTION_ID] = NEUTRAL_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][STUNNED_ACTION_ID] = STUNNED_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PERFECT_MOMENTUM_STOP_BLOCK_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][REBOUND_CLASH_BREAK_ACTION_ID] = REBOUND_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ON_HIT_BACK_TOOL_ACTION_ID] = ON_HIT_BACK_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_TOOL_COUNTER_HIT_ACTION_ID] = NEUTRAL_TOOL_COUNTER_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UP_TOOL_NORMAL_ACTION_ID] = UPWARD_TOOL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][UP_TOOL_REKA_ACTION_ID] = UP_TOOL_REKA_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UP_TOOL_ON_HIT_ACTION_ID] = UP_TOOL_ON_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UP_TOOL_REKA_ON_HIT_ACTION_ID] = UP_TOOL_REKA_ON_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ON_HIT_F_SPECIAL_MOMENTUM_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][MOMENTUM_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][CORNER_HITTING_PUSH_AWAY_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][BASIC_CROUCH_CANCEL_ACTION_ID] = BASIC_CROUCH_CANCEL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BREAK_FROM_HITSTUN_HALT_ACTION_ID] = null	
	animationLookup[SPRITE_ANIME_IX][NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID] = NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID] = NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID] = NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][FORWARD_SPECIAL_ON_HIT_STOP_ACTION_ID] = null	
	animationLookup[SPRITE_ANIME_IX][INVULNERABLE_GUARD_BREAK_ACTION_ID] = INVULNERABLE_GUARD_BREAK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GRAB_CANCEL_MOMENTUM_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][GETTING_PUSH_BLOCKED_IN_NEUTRAL_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][FORWARD_TOOL_REKA_ACTION_ID] = FORWARD_TOOL_REKA_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_TOOL_NORMAL_ACTION_ID] = FORWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_TOOL_REKA_ON_HITACTION_ID] = FORWARD_TOOL_REKA_ON_HIT_SPRITE_ANIME_ID
	
	animationLookup[SPRITE_ANIME_IX][ANGRY_D_TOOL_ACTION_ID] = ANGRY_D_TOOL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ANGRY_B_SPECIAL_ACTION_ID] = ANGRY_B_SPECIAL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ANGRY_D_SPECIAL_ACTION_ID] = ANGRY_D_SPECIAL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ANGRY_F_SPECIAL_ACTION_ID] = ANGRY_F_SPECIAL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ANGRY_N_SPECIAL_ACTION_ID] = ANGRY_N_SPECIAL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ANGRY_U_SPECIAL_ACTION_ID] = ANGRY_U_SPECIAL_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ANGRY_AIR_SPECIAL_ACTION_ID] = ANGRY_AIR_SPECIAL_SPRITE_ANIME_ID	



	animationLookup[MVM_ANIME_IX][JUMP_ACTION_ID]=JUMP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][JUMP_ACTION_ID]=TEST_CIRCULAR_MOVE_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][AIR_JUMP_ACTION_ID]=JUMP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][AIR_MOVE_FORWARD_ACTION_ID]=AIR_MOVE_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_MOVE_BACKWARD_ACTION_ID]=AIR_MOVE_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_IDLE_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID #no movement assosiated
	animationLookup[MVM_ANIME_IX][GROUND_MOVE_FORWARD_ACTION_ID]=GROUND_MOVE_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_MOVE_BACKWARD_ACTION_ID]=GROUND_MOVE_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_IDLE_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][SLIDING_GROUND_IDLE_ACTION_ID]=GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][SLIDING_AIR_IDLE_ACTION_ID]=AIR_KEEP_MOMENTUM_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][AIR_DASH_FORWARD_ACTION_ID]=AIR_DASH_FORWARD_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][AIR_DASH_BACKWARD_ACTION_ID]=AIR_DASH_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_MELEE_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_MELEE_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_SPECIAL_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_SPECIAL_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][REBOUND_ACTION_ID]=REBOUND_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][REBOUND_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][REBOUND_CLASH_BREAK_VICTIM_ACTION_ID]=REBOUND_CLASH_BREAK_VICTIM_MVM_ANIME_ID	
	#animationLookup[MVM_ANIME_IX][REBOUND_CLASH_BREAK_VICTIM_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID		
	animationLookup[MVM_ANIME_IX][CROUCH_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][JUMP_FORWARD_ACTION_ID]=JUMP_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][JUMP_BACKWARD_ACTION_ID]=JUMP_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_JUMP_FORWARD_ACTION_ID]=JUMP_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_JUMP_BACKWARD_ACTION_ID]=JUMP_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_DASH_DOWNWARD_ACTION_ID]=AIR_DASH_DOWNWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_TOOL_ACTION_ID]=AIR_TOOL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_TOOL_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_RIPOST_ACTION_ID]=RIPOST_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][GROUND_RIPOST_ACTION_ID]=RIPOST_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AUTO_RIPOST_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_AUTO_RIPOST_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AUTO_RIPOST_ON_HIT_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_AUTO_RIPOST_ON_HIT_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][HITSTUN_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][AIR_MOVE_STOP_ACTION_ID] = AIR_MOVE_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACKWARD_SPECIAL_ACTION_ID] = BACK_SPECIAL_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][LANDING_STOP_MOMENTUM_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LANDING_STOP_MOMENTUM_ACTION_ID]=LANDING_LAG_MVM_ANIME_ID #**********
	#animationLookup[MVM_ANIME_IX][LANDING_LAG_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LANDING_LAG_ACTION_ID]=LANDING_LAG_MVM_ANIME_ID	#*********
	animationLookup[MVM_ANIME_IX][DOWNWARD_MELEE_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_SPECIAL_ACTION_ID]=FORWARD_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UPWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LANDING_HITSTUN_ACTION_ID]=OKI_MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_ACTION_ID]=WALL_BOUNCE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][INVULNERABLE_AIR_HITSTUN_ACTION_ID] = INVULNERABLE_HITSTUN_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACKWARD_TOOL_ACTION_ID] = BACKWARD_TOOL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_MELEE_ACTION_ID] = FORWARD_MELEE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_FORWARD_DASH_ACTION_ID] = GROUND_FORWARD_DASH_MVM_ANIME_ID
	
	
	animationLookup[MVM_ANIME_IX][GROUND_BACKWARD_DASH_ACTION_ID] = GROUND_BACKWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_ACTION_ID] = ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_ACTION_ID] = GROUND_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_SPECIAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UPWARD_SPECIAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_IN_PLACE_TECH_ACTION_ID] = GROUND_IN_PLACE_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_BOUNCE_UP_TECH_ACTION_ID] = GROUND_TECH_BOUNCE_UP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_UP_TECH_ACTION_ID] = WALL_TECH_BOUNCE_UP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_DOWN_TECH_ACTION_ID] = WALL_TECH_BOUNCE_DOWN_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_AWAY_TECH_ACTION_ID] = WALL_TECH_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][ROLLING_BACKWARD_TECH_ACTION_ID] = TECH_ROLL_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ROLLING_FORWARD_TECH_ACTION_ID] = TECH_ROLL_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_BOUNCE_BACK_TECH_ACTION_ID] = CEILING_BOUNCE_BACK_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_BOUNCE_FORWARD_TECH_ACTION_ID] = CEILING_BOUNCE_FORWARD_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_TECH_ACTION_ID] = AIR_TECH_IN_PLACE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_BOUNCE_DOWN_TECH_ACTION_ID] = CEILING_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_TECH_ACTION_ID] = AIR_TECH_IN_PLACE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UPWARD_MELEE_ACTION_ID] = UP_MELEE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_TOOL_ACTION_ID] =FORWARD_TOOL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACKWARD_MELEE_ACTION_ID] = BACKWARD_MELEE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_HITSTUN_ACTION_ID] = null
	#animationLookup[MVM_ANIME_IX][BUDGET_BLOCK_HIT_LAG_ACTION_ID] = GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BUDGET_BLOCK_HIT_LAG_ACTION_ID] = null
	#animationLookup[MVM_ANIME_IX][AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = AIR_BLOCK_STUN_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_STOP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][LEAVE_PLATFROM_HALT_ACTION_ID] = LEAVE_PLATFROM_HALT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LAND_ON_PLATFROM_ACTION_ID] = LAND_ON_PLATFROM_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_HITSTUN_BREAK_FREE_ACTION_ID] = AIR_HITSTUN_BREAK_FREE_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][STOP_PLATFORM_LEAVE_MOMENTUM_ACTION_ID] = STOP_PLATFORM_LEAVE_MOMENTUM_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PLATFORM_DROP_ACTION_ID] = PLATFORM_DROP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PLATFORM_ANIMATION_CANCEL_ACTION_ID] = STOP_PLATFORM_LEAVE_MOMENTUM_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UNCROUCH_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ON_HIT_GROUND_GRAB_ACTION_ID] = ON_HIT_GROUND_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ON_HIT_AIR_GRAB_ACTION_ID] = ON_HIT_AIR_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = F_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = B_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][GETTING_PUSH_BLOCKED_ACTION_ID] = PUSH_BLOCK_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_PUSH_BLOCKING_ACTION_ID] = NON_MVM_PUSH_BLOCKING_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_PUSH_BLOCKING_ACTION_ID] = NON_MVM_PUSH_BLOCKING_MVM_ANIME_ID
#	animationLookup[MVM_ANIME_IX][GROUND_PUSH_BLOCKING_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
#	animationLookup[MVM_ANIME_IX][AIR_PUSH_BLOCKING_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_UP_THROW_ACTION_ID] = GROUND_GRAB_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_FORWARD_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_DOWN_THROW_ACTION_ID] = GROUND_GRAB_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_BACKWARD_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_NEUTRAL_THROW_ACTION_ID] = GROUND_GRAB_NEUTRAL_THROW_MVM_ANIME_ID

	animationLookup[MVM_ANIME_IX][AIR_GRAB_UP_THROW_ACTION_ID] = AIR_GRAB_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_FORWARD_UP_THROW_ACTION_ID] = AIR_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_FORWARD_THROW_ACTION_ID] = AIR_GRAB_FORWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = AIR_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_DOWN_THROW_ACTION_ID] = AIR_GRAB_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_BACKWARD_THROW_ACTION_ID] = AIR_GRAB_BACKWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = AIR_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID] = AIR_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_NEUTRAL_THROW_ACTION_ID] = AIR_GRAB_NEUTRAL_THROW_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID] = GROUND_FORWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID] = GROUND_BACKWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][APEX_ONLY_FAST_FALL_ACTION_ID] = AIR_DASH_DOWNWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID] = AIR_BLOCK_STUN_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][STUNNED_ACTION_ID] = STUNNED_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][PERFECT_MOMENTUM_STOP_BLOCK_ACTION_ID] = PERFECT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][REBOUND_CLASH_BREAK_ACTION_ID] = REBOUND_CLASH_BREAK_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][ON_HIT_BACK_TOOL_ACTION_ID] = ON_HIT_BACK_TOOL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_TOOL_COUNTER_HIT_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UP_TOOL_NORMAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][ON_HIT_F_SPECIAL_MOMENTUM_STOP_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][MOMENTUM_STOP_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CORNER_HITTING_PUSH_AWAY_ACTION_ID] = CORNER_HITTING_PUSH_AWAY_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BASIC_CROUCH_CANCEL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BREAK_FROM_HITSTUN_HALT_ACTION_ID] = BREAK_FROM_HITSTUN_HALT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID] = JUMP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID] = JUMP_FORWARD_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID] = JUMP_BACKWARD_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][FORWARD_SPECIAL_ON_HIT_STOP_ACTION_ID] = FORWARD_SPECIAL_STOP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][INVULNERABLE_GUARD_BREAK_ACTION_ID] = INVULNERABLE_GUARD_BREAK_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][GRAB_CANCEL_MOMENTUM_STOP_ACTION_ID] = GRAB_CANCEL_MOMENTUM_STOP_MVM_ANIME_ID	

	
	
	animationLookup[MVM_ANIME_IX][FORWARD_TOOL_REKA_ACTION_ID] = animationLookup[MVM_ANIME_IX][FORWARD_TOOL_ACTION_ID]
	animationLookup[MVM_ANIME_IX][FORWARD_TOOL_REKA_ON_HITACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
		
	animationLookup[MVM_ANIME_IX][FORWARD_TOOL_NORMAL_ACTION_ID] = animationLookup[MVM_ANIME_IX][FORWARD_TOOL_ACTION_ID]
	
	animationLookup[MVM_ANIME_IX][UP_TOOL_REKA_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UP_TOOL_ON_HIT_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UP_TOOL_REKA_ON_HIT_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	
	
	
	animationLookup[MVM_ANIME_IX][ANGRY_D_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ANGRY_B_SPECIAL_ACTION_ID] = ANGRY_B_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ANGRY_D_SPECIAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ANGRY_F_SPECIAL_ACTION_ID] = ANGRY_F_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ANGRY_N_SPECIAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][ANGRY_U_SPECIAL_ACTION_ID] = ANGRY_U_SPECIAL_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][ANGRY_AIR_SPECIAL_ACTION_ID] = ANGRY_AIR_SPECIAL_MVM_ANIME_ID	
		
	animationLookup[MVM_ANIME_IX][GETTING_PUSH_BLOCKED_IN_NEUTRAL_ACTION_ID]=GETTING_PUSH_BLOCKED_IN_NEUTRAL_MVM_ANIME_ID
	

	#make a backup of the map of animations	
	for actionId in animationLookup[SPRITE_ANIME_IX].keys():
		animationLookupDefault[SPRITE_ANIME_IX][actionId]=animationLookup[SPRITE_ANIME_IX][actionId]
	for actionId in animationLookup[MVM_ANIME_IX].keys():
		animationLookupDefault[MVM_ANIME_IX][actionId]=animationLookup[MVM_ANIME_IX][actionId]
	
	
	pushBlockActionIdWhiteList.append(AIR_DASH_BACKWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_DASH_FORWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_DASH_DOWNWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(JUMP_FORWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(JUMP_BACKWARD_ACTION_ID)			
	pushBlockActionIdWhiteList.append(NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID)		
	pushBlockActionIdWhiteList.append(AIR_JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_JUMP_FORWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_JUMP_BACKWARD_ACTION_ID)		
	pushBlockActionIdWhiteList.append(GROUND_FORWARD_DASH_ACTION_ID)
	pushBlockActionIdWhiteList.append(GROUND_BACKWARD_DASH_ACTION_ID)		
	pushBlockActionIdWhiteList.append(NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID)
	pushBlockActionIdWhiteList.append(NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID)		
	

	onHitLoseAngryAnimes[ANGRY_B_SPECIAL_SPRITE_ANIME_ID]=null
	onHitLoseAngryAnimes[ANGRY_AIR_SPECIAL_SPRITE_ANIME_ID]=null
	onHitLoseAngryAnimes[ANGRY_F_SPECIAL_SPRITE_ANIME_ID]=null
	onHitLoseAngryAnimes[ANGRY_D_SPECIAL_SPRITE_ANIME_ID]=null
	onHitLoseAngryAnimes[ANGRY_U_SPECIAL_SPRITE_ANIME_ID]=null
	onHitLoseAngryAnimes[ANGRY_N_SPECIAL_SPRITE_ANIME_ID]=null
	
	#sprite aniamtion ids to keep track of frames durations, null value since only need key for lookup
	frameTrackingSpriteAnimationIdMap[BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[PUSH_BLOCK_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[STUNNED_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[LANDING_HITSTUN_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[REBOUND_SPRITE_ANIME_ID]=null
	

	#animationLookup[MVM_ANIME_IX][DELAYED_N_MELEE_1_ACTION_ID] = GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][DELAYED_N_MELEE_2_ACTION_ID] = GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID
	
	#populate the command lookup map
	#melees
	commandLookupMap[AIR_NEUTRAL_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_MELEE
	commandLookupMap[NEUTRAL_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_MELEE
	commandLookupMap[BACKWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_MELEE
	commandLookupMap[FORWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_MELEE
	commandLookupMap[DOWNWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_MELEE
	commandLookupMap[UPWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_MELEE
	#specials
	commandLookupMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[NEUTRAL_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[BACKWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_SPECIAL
	commandLookupMap[FORWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_SPECIAL
	commandLookupMap[DOWNWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_SPECIAL
	commandLookupMap[UPWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_SPECIAL
	commandLookupMap[ANGRY_B_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_SPECIAL
	commandLookupMap[ANGRY_D_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_SPECIAL
	commandLookupMap[ANGRY_N_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[ANGRY_F_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_SPECIAL
	commandLookupMap[ANGRY_U_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_SPECIAL
	commandLookupMap[ANGRY_AIR_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL

	#tools
	commandLookupMap[AIR_NEUTRAL_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_TOOL
	commandLookupMap[NEUTRAL_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_TOOL
	commandLookupMap[BACKWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_TOOL
	commandLookupMap[FORWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_TOOL
	commandLookupMap[DOWNWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_TOOL
	commandLookupMap[ANGRY_D_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_TOOL
	commandLookupMap[UPWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_TOOL
	commandLookupMap[UP_TOOL_REKA_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_TOOL
	commandLookupMap[UP_TOOL_NORMAL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_TOOL
	commandLookupMap[FORWARD_TOOL_REKA_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_TOOL
	commandLookupMap[FORWARD_TOOL_NORMAL_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_TOOL		
	
	#movement
	commandLookupMap[JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP
	commandLookupMap[JUMP_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_FORWARD
	commandLookupMap[JUMP_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_BACKWARD
	
	commandLookupMap[AIR_MOVE_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_FORWARD
	commandLookupMap[AIR_MOVE_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_BACKWARD
	
	commandLookupMap[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP
	commandLookupMap[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_FORWARD
	commandLookupMap[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_BACKWARD
	
	
	commandLookupMap[AIR_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP
	commandLookupMap[AIR_JUMP_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_FORWARD
	commandLookupMap[AIR_JUMP_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_BACKWARD
	
	
	commandLookupMap[GROUND_MOVE_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_FORWARD
	commandLookupMap[GROUND_MOVE_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_BACKWARD
	commandLookupMap[AIR_DASH_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_DASH_FORWARD
	commandLookupMap[AIR_DASH_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_DASH_BACKWARD
	commandLookupMap[GROUND_FORWARD_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_FORWARD
	commandLookupMap[GROUND_BACKWARD_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_BACKWARD
	commandLookupMap[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_FORWARD
	commandLookupMap[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_BACKWARD
	commandLookupMap[AIR_DASH_DOWNWARD_ACTION_ID]=inputManagerResource.Command.CMD_AIR_DASH_DOWNWARD
	commandLookupMap[APEX_ONLY_FAST_FALL_ACTION_ID]=inputManagerResource.Command.CMD_AIR_DASH_DOWNWARD
	#other
	commandLookupMap[CROUCH_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	commandLookupMap[UNCROUCH_ACTION_ID]=inputManagerResource.Command.CMD_STOP_CROUCH
	commandLookupMap[AUTO_RIPOST_ACTION_ID]=inputManagerResource.Command.CMD_AUTO_RIPOST
	commandLookupMap[AIR_AUTO_RIPOST_ACTION_ID]=inputManagerResource.Command.CMD_AUTO_RIPOST
	commandLookupMap[GROUND_GRAB_ACTION_ID]=inputManagerResource.Command.CMD_GRAB
	commandLookupMap[AIR_GRAB_ACTION_ID]=inputManagerResource.Command.CMD_GRAB
	commandLookupMap[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	commandLookupMap[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	commandLookupMap[BASIC_CROUCH_CANCEL_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	
	#commandLookupMap[PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_CROUCH	
	
	#commands that can't be used for counter ripost
	#counterRipostCmdBlackListMap[inputManagerResource.Command.CMD_UPWARD_SPECIAL]=null  #null, since only key is used	

	pushBlockSpriteAnimeIds.append(PUSH_BLOCK_SPRITE_ANIME_ID)
	
	techSpriteAnimeIds.append(BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(CEILING_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(FORWARD_ROLLING_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(WALL_TECH_SPRITE_ANIME_ID)
	
	reversalSpriteAnimationIdMap[UPWARD_SPECIAL_SPRITE_ANIME_ID] = null#DP
	reversalSpriteAnimationIdMap[AUTO_RIPOST_SPRITE_ANIME_ID] = null #alpha counter
	
	
	reversableSpriteAnimationIdMap[HITSTUN_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[LANDING_HITSTUN_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[AIR_HITSTUN_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[REBOUND_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[FORWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[CEILING_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[WALL_TECH_SPRITE_ANIME_ID]=null
	
	invincibilitySpriteAnimationIdMap[AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[UPWARD_SPECIAL_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[RIPOST_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[ANGRY_D_TOOL_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[WALL_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[CEILING_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[INVULNERABLE_GUARD_BREAK_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[FORWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null	
	invincibilitySpriteAnimationIdMap[NEUTRAL_TOOL_COUNTER_HIT_ACTION_ID]=null	
	
	
	techSpriteAnimationIdsMap[GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[FORWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[CEILING_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[WALL_TECH_SPRITE_ANIME_ID]=null
	
	
	airBornSupportPreventAutoFacingSpriteAnimeIds[ANGRY_AIR_SPECIAL_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[EXPIRED_AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID]=null
	
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_IDLE_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[JUMP_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_JUMP_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID]=null			
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_DASH_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[BACK_AIR_DASH_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[GROUND_GRAB_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_GRAB_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[AUTO_RIPOST_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID]=null
	
		#populate map to lookup action names
	#USED for combo list in pause hud
	actionIdNameMap[AIR_NEUTRAL_MELEE_ACTION_ID]="Aerial punch"
	actionIdNameMap[NEUTRAL_MELEE_ACTION_ID]="Punch"
	actionIdNameMap[BACKWARD_MELEE_ACTION_ID]="Straight Kick"
	actionIdNameMap[FORWARD_MELEE_ACTION_ID]="Step Punch"
	actionIdNameMap[DOWNWARD_MELEE_ACTION_ID]="Knife Hand Chop"
	actionIdNameMap[UPWARD_MELEE_ACTION_ID]="Axe Kick"
	#specials
	actionIdNameMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]="Calm Down"
	actionIdNameMap[ANGRY_AIR_SPECIAL_ACTION_ID]="Calm Down"	
	actionIdNameMap[NEUTRAL_SPECIAL_ACTION_ID]="You had this one coming!"
	actionIdNameMap[BACKWARD_SPECIAL_ACTION_ID]="You're not blocking this one!"
	actionIdNameMap[ANGRY_B_SPECIAL_ACTION_ID]="You're not blocking this one!"
	actionIdNameMap[ANGRY_D_SPECIAL_ACTION_ID]="I'm bringing you down!"
	actionIdNameMap[FORWARD_SPECIAL_ACTION_ID]="I'm coming for you!"
	actionIdNameMap[ANGRY_N_SPECIAL_ACTION_ID]="You had this one coming!"
	actionIdNameMap[ANGRY_F_SPECIAL_ACTION_ID]="I'm coming for you!"
	actionIdNameMap[DOWNWARD_SPECIAL_ACTION_ID]="I'm bringing you down!"
	actionIdNameMap[UPWARD_SPECIAL_ACTION_ID]="It won't be that easy!"
	actionIdNameMap[ANGRY_U_SPECIAL_ACTION_ID]="Get up there!"
	#tools
	actionIdNameMap[AIR_NEUTRAL_TOOL_ACTION_ID]="You're coming with me"
	actionIdNameMap[NEUTRAL_TOOL_ACTION_ID]="Tightening the Belt"
	actionIdNameMap[BACKWARD_TOOL_ACTION_ID]="If you won't come at me...."
	actionIdNameMap[FORWARD_TOOL_ACTION_ID]="You won't get away that easy, Hat!"
	actionIdNameMap[DOWNWARD_TOOL_ACTION_ID]="Getting annoyed!"
	actionIdNameMap[ANGRY_D_TOOL_ACTION_ID]="Calming down"	
	actionIdNameMap[UPWARD_TOOL_ACTION_ID]="Loosening the Belt"
	actionIdNameMap[UP_TOOL_NORMAL_ACTION_ID]="Loosening the Belt"
	actionIdNameMap[UP_TOOL_REKA_ACTION_ID]="Loosening the Belt (become Angry) "
	actionIdNameMap[FORWARD_TOOL_REKA_ACTION_ID]="You won't get away that easy, Hat! (become Angry)"
	
	
	#movement
	actionIdNameMap[JUMP_ACTION_ID]="Jump"
	actionIdNameMap[JUMP_FORWARD_ACTION_ID]="Forward Jump"
	actionIdNameMap[JUMP_BACKWARD_ACTION_ID]="Back Jump"
	
	actionIdNameMap[AIR_JUMP_ACTION_ID]="Air Jump"
	actionIdNameMap[AIR_JUMP_FORWARD_ACTION_ID]="Air Forward Jump"
	actionIdNameMap[AIR_JUMP_BACKWARD_ACTION_ID]="Air Back Jump"
	
	actionIdNameMap[AIR_MOVE_FORWARD_ACTION_ID]="Move forward"
	actionIdNameMap[AIR_MOVE_BACKWARD_ACTION_ID]="Move backward"
	
	actionIdNameMap[GROUND_MOVE_FORWARD_ACTION_ID]="Move forward"
	actionIdNameMap[GROUND_MOVE_BACKWARD_ACTION_ID]="Move backward"
	
	actionIdNameMap[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID]="Jump"
	actionIdNameMap[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID]="Forward Jump"
	actionIdNameMap[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID]="Back Jump"
	
	
	actionIdNameMap[AIR_DASH_FORWARD_ACTION_ID]="Air Forward Dash"
	actionIdNameMap[AIR_DASH_BACKWARD_ACTION_ID]="Air Back Dash"
	actionIdNameMap[GROUND_FORWARD_DASH_ACTION_ID]="Ground Forward Dash"
	actionIdNameMap[GROUND_BACKWARD_DASH_ACTION_ID]="Ground Back Dash"
	actionIdNameMap[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]="Ground Forward Dash"
	actionIdNameMap[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]="Ground Back Dash"
	actionIdNameMap[AIR_DASH_DOWNWARD_ACTION_ID]="Instant Fast Fall"
	actionIdNameMap[APEX_ONLY_FAST_FALL_ACTION_ID]="Fast Fall"
	actionIdNameMap[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]="Crouch Cancel"
	actionIdNameMap[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]="Crouch Cancel"	
	actionIdNameMap[BASIC_CROUCH_CANCEL_ACTION_ID]="Crouch Cancel"	
	
	actionIdNameMap[CROUCH_ACTION_ID]="Crouch"
	actionIdNameMap[AUTO_RIPOST_ACTION_ID]="Auto Ripost"
	actionIdNameMap[AIR_AUTO_RIPOST_ACTION_ID]="Air Auto Ripost"
	actionIdNameMap[GROUND_GRAB_ACTION_ID]="Grab"
	actionIdNameMap[AIR_GRAB_ACTION_ID]="Grab"
	
	

	
	
	
	#populate map to lookup action details
	#USED for combo list in pause hud
	actionIdDetailsMap[AIR_NEUTRAL_MELEE_ACTION_ID]="Light quick air punch. Sends the opponent slightly in front and upward"
	actionIdDetailsMap[NEUTRAL_MELEE_ACTION_ID]="Light quick very short-ranged standing punch. Sends the opponent slightly in front and upward"
	actionIdDetailsMap[BACKWARD_MELEE_ACTION_ID]="Light standing short-ranged straight kick. Keeps the opponent in-place"
	actionIdDetailsMap[FORWARD_MELEE_ACTION_ID]="Light slightly advancing short/medium ranged punch. Keeps the opponent in-place"
	actionIdDetailsMap[DOWNWARD_MELEE_ACTION_ID]="Light quick medium-ranged hand chop\n (low). Keeps the opponent in-place"
	actionIdDetailsMap[UPWARD_MELEE_ACTION_ID]="Light short/medium-ranged 2-hit hopping anti-air kick that causes a re-stand, making it ideal to continue an air-based combo into a ground combo. \n\nThe first hit has a meaty hitbox"
	#specials
	actionIdDetailsMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]="Heavy air kick that causes the opponent to slow fall for a long duration, making it ideal to setup into any combo (especially with a fast fall).  \n\n Most properties of this kick can be used 1/combo before becoming stale (see the 'Calm Down (stale)' move). An ability cancel refreshes it."
	actionIdDetailsMap[NEUTRAL_SPECIAL_ACTION_ID]="Heavy long-startup long-reaching extending punch that causes a lot of guard damage and pressure. The opponent is sent flying horizontally accross the screen, making it an ideal attack to get your opponent into a corner."
	actionIdDetailsMap[BACKWARD_SPECIAL_ACTION_ID]="Belt quickly takes a short step back and then advances back to the same position with a medium lunging standing kick. The opponent flying slowly horizontally at a slight upward angle. "
	actionIdDetailsMap[ANGRY_B_SPECIAL_ACTION_ID]="Belt takes a large step back and then advances back to the same position with a heavy lunging standing kick. The opponent flying slowly horizontally at a slight upward angle. On hit Belt becomes calm."
	actionIdDetailsMap[ANGRY_D_SPECIAL_ACTION_ID]="The Angry version of 'I'm bringing you down!', which is identical to its Calm version, but instead of knocking the opponent onto the ground, it bounces them up into the air slightly, enabling the potential to combo off of this attack. On hit Belt becomes calm."
	actionIdDetailsMap[FORWARD_SPECIAL_ACTION_ID]="A medium lunging punch that covers a fraction of the screen. The opponent flying slowly horizontally at a slight upward angle. "
	actionIdDetailsMap[ANGRY_N_SPECIAL_ACTION_ID]="The Angry version of 'You had this one coming!', but can now be canceled at any point using a crouch cancel at the cost of giving up the Angry stance and becoming Calm. On hit Belt becomes calm."
	actionIdDetailsMap[ANGRY_F_SPECIAL_ACTION_ID]="The Angry version of 'I'm coming for you!', but covers most of the screen instead of only a portion, and does slightly more guard damage. On hit Belt becomes calm."
	actionIdDetailsMap[DOWNWARD_SPECIAL_ACTION_ID]="Medium standing sweeping kick that resets the combo by tripping the opponent onto the ground. It is ideal for finishing a combo."
	actionIdDetailsMap[UPWARD_SPECIAL_ACTION_ID]="Short/medium range quick heavy anti-air invincible instant reversal. It has large recovery and is punishable on block. Sends the opponent flying accross the screen to bounce off the walls/ceilings and then knocks them down near you."
	actionIdDetailsMap[ANGRY_U_SPECIAL_ACTION_ID]="Short/medium range heavy anti-air that has good block pressure.  Belt hops into the air and kicks upward. On-hit Belt has decent air movement mix-up options. On hit Belt becomes calm."
	actionIdDetailsMap[ANGRY_AIR_SPECIAL_ACTION_ID]="The Angry version of 'Calm Down', but keeps you airborn momentarily, does a bit more guard damage, and doesn't suffer from stale moves (can hit with air special a 2nd time) On hit Belt becomes calm."
	

	#tools
	actionIdDetailsMap[AIR_NEUTRAL_TOOL_ACTION_ID]="Heavy aerial downward dive kick that kicks the opponent diagonally downward, bouncing the opponent off the ground and setting up Belt for high-reaching attacks to followup."
	actionIdDetailsMap[NEUTRAL_TOOL_ACTION_ID]="Standing counter stance that parries when hit by an attack (weak to grab). When the parry is triggerd, Belt becomes Angry. The timing to this parry is tight, since it is not immideatly active when the animation ends. The oppoent is kept in place when hit and generally cannot be used to combo. )"
	actionIdDetailsMap[BACKWARD_TOOL_ACTION_ID]="The start of this animation is the same as 'Tightening the Belt' to fakeout a parry. Belt lunges forward for a fraction of the screen and if the opponent is in range she does a heavy upper-cut punch. The opponent is sent flying away and can bounce the opponent off a wall, making corner combos quite effective. \n\n Anrgy: if Belt is Angry, whiffing this attack makes her become Calm."
	actionIdDetailsMap[FORWARD_TOOL_ACTION_ID]="Heavy long range belt whip attack that only has a hitbox at the tip of the belt. It knocks the opponent down."
	actionIdDetailsMap[DOWNWARD_TOOL_ACTION_ID]="A standing ground stomp that can only hit opponents that are knocked down. A great way to mix up the timing of your combos to throw off your opponent."
	actionIdDetailsMap[ANGRY_D_TOOL_ACTION_ID]="Belt becomes intangible. She cannot be pushed, the opponents faze through her (can walk throught her), and she cannot be attacked for a short period of time. At any point Belt can act out of this animation. \n\nBelt becomes Calm after using this animation"
	actionIdDetailsMap[UPWARD_TOOL_ACTION_ID]="Medium-to-long range standing belt lasso diagonal upward anti-air whip lasso. Belt's lasso grapples any opponent in the air, making it an unblockable anti-air, and it pulls them in towards her. If Belt is hit during the pull, the opponent break free."
	actionIdDetailsMap[UP_TOOL_NORMAL_ACTION_ID]="Medium-to-long range standing belt lasso diagonal upward anti-air whip lasso. Belt's lasso grapples any opponent in the air, making it an unblockable anti-air, and it pulls them in towards her. If Belt is hit during the pull, the opponent break free."
	actionIdDetailsMap[UP_TOOL_REKA_ACTION_ID]="Has similar properties to 'Loosening the Belt'. What is differentd is it pulls them in towards Belt and the opponent ends up in front and above her and it does a bit less damage. This attack will drop the combo and Belt will become Angry (useful to end a combo)."
	actionIdDetailsMap[FORWARD_TOOL_REKA_ACTION_ID]="Has similar properties to 'You won't get away that easy, Hat!'. What is differentd is Belt will become Angry and ends +0."
	
	
	#movement
	actionIdDetailsMap[JUMP_ACTION_ID]="Jump (some actions can be done in short \n startup window before upward momentum)"
	actionIdDetailsMap[JUMP_FORWARD_ACTION_ID]="Forward jump (some actions can be done in short \n startup window before upward momentum)"
	actionIdDetailsMap[JUMP_BACKWARD_ACTION_ID]="Back jump (some actions can be done in short \n startup window before upward momentum)"
	
	actionIdDetailsMap[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID]="Jump (some actions, not ground dash, can be done in short \n startup window before upward momentum)"
	actionIdDetailsMap[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID]="Forward jump (some actions, not ground dash, can be done in short \n startup window before upward momentum)"
	actionIdDetailsMap[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID]="Back jump (some actions, not ground dash, can be done in short \n startup window before upward momentum)"

	
	actionIdDetailsMap[AIR_JUMP_ACTION_ID]="Aerial jump (some actions can be done in short \n startup window before upward momentum)"
	actionIdDetailsMap[AIR_JUMP_FORWARD_ACTION_ID]="Aerial forward jump (some actions can be done in short \n startup window before upward momentum)"
	actionIdDetailsMap[AIR_JUMP_BACKWARD_ACTION_ID]="Aerial back jump (some actions can be done in short \n startup window before upward momentum)"
	
	actionIdDetailsMap[AIR_DASH_FORWARD_ACTION_ID]="Forward Air Dash"
	actionIdDetailsMap[AIR_DASH_BACKWARD_ACTION_ID]="Back Air Dash"
	actionIdDetailsMap[GROUND_FORWARD_DASH_ACTION_ID]="Crouch cancelable forward ground dash \n (inputing 'crouch' will cancel the dash)"
	actionIdDetailsMap[GROUND_BACKWARD_DASH_ACTION_ID]="Crouch cancelable back ground dash \n (inputing 'crouch' will cancel the dash)"
	actionIdDetailsMap[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]="forward ground dash"
	actionIdDetailsMap[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]="back ground dash"
	actionIdDetailsMap[AIR_DASH_DOWNWARD_ACTION_ID]="Instantly start falling without interrupting current animation"
	actionIdDetailsMap[APEX_ONLY_FAST_FALL_ACTION_ID]="Upong reaching apex of jump, instantly start falling \n without interrupting current animation"
	actionIdDetailsMap[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]="Short recovery period after canceling a f-dash"
	actionIdDetailsMap[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]="Short recovery period after canceling a b-dash"
	actionIdDetailsMap[BASIC_CROUCH_CANCEL_ACTION_ID]="Brief recovery upon canceling a special animtion with crouch"
	
	actionIdDetailsMap[CROUCH_ACTION_ID]="Crouch"
	actionIdDetailsMap[AUTO_RIPOST_ACTION_ID]="A counter that upon being hit instantly leads into a combo \n (non-grab invincibility,counter)"
	actionIdDetailsMap[AIR_AUTO_RIPOST_ACTION_ID]="A counter that upon being hit instantly leads into a combo \n (non-grab invincibility,counter)"
	#actionIdDetailsMap[GROUND_GRAB_ACTION_ID]="Non damaging move that after grabbing an opponent, can input \n any of the 8 directional inputs to move the opponent (grab)"
	#actionIdDetailsMap[AIR_GRAB_ACTION_ID]="Non damaging move that after grabbing an opponent, can input \n any of the 8 directional inputs to move the opponent (grab)"
	
	
	airActionIdMap[AIR_AUTO_RIPOST_ACTION_ID]=null
	airActionIdMap[AIR_AUTO_RIPOST_ON_HIT_ACTION_ID]=null
	airActionIdMap[AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID]=null
	airActionIdMap[AIR_DASH_BACKWARD_ACTION_ID]=null
	airActionIdMap[AIR_DASH_FORWARD_ACTION_ID]=null
	airActionIdMap[AIR_DASH_DOWNWARD_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_BACKWARD_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_NEUTRAL_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_DOWN_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_FORWARD_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_FORWARD_UP_THROW_ACTION_ID]=null
	airActionIdMap[AIR_HITSTUN_ACTION_ID]=null
	airActionIdMap[AIR_HITSTUN_BREAK_FREE_ACTION_ID]=null
	airActionIdMap[AIR_IDLE_ACTION_ID]=null
	airActionIdMap[AIR_JUMP_ACTION_ID]=null
	airActionIdMap[AIR_JUMP_BACKWARD_ACTION_ID]=null
	airActionIdMap[AIR_JUMP_FORWARD_ACTION_ID]=null
	airActionIdMap[AIR_MOVE_BACKWARD_ACTION_ID]=null
	airActionIdMap[AIR_MOVE_FORWARD_ACTION_ID]=null
	airActionIdMap[AIR_MOVE_STOP_ACTION_ID]=null
	airActionIdMap[AIR_NEUTRAL_MELEE_ACTION_ID]=null
	airActionIdMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=null
	airActionIdMap[AIR_NEUTRAL_TOOL_ACTION_ID]=null
	airActionIdMap[AIR_RIPOST_ACTION_ID]=null
	
	
	
	autoCancelMaskMap[JUMP_ACTION_ID]=1 #bitshift 0
	autoCancelMaskMap[JUMP_FORWARD_ACTION_ID]=1 << 1 #2
	autoCancelMaskMap[JUMP_BACKWARD_ACTION_ID]=1 << 2#4
	autoCancelMaskMap[GROUND_IDLE_ACTION_ID]=1 << 3 #8
	autoCancelMaskMap[SLIDING_GROUND_IDLE_ACTION_ID]=1 << 3 #SAME AS ground idle	
	autoCancelMaskMap[GROUND_MOVE_FORWARD_ACTION_ID]=1 << 4 #16
	autoCancelMaskMap[GROUND_MOVE_BACKWARD_ACTION_ID]=1 << 5 #32...
	autoCancelMaskMap[CROUCH_ACTION_ID]=1 << 6
	autoCancelMaskMap[NEUTRAL_MELEE_ACTION_ID]=1 << 7
	autoCancelMaskMap[NEUTRAL_SPECIAL_ACTION_ID]=1 << 8
	autoCancelMaskMap[NEUTRAL_TOOL_ACTION_ID]=1 << 9
	autoCancelMaskMap[BACKWARD_SPECIAL_ACTION_ID] = 1 << 10
	autoCancelMaskMap[AUTO_RIPOST_ACTION_ID]=1 << 11
	
	autoCancelMaskMap[AIR_IDLE_ACTION_ID]=1 << 12
	autoCancelMaskMap[AIR_MOVE_FORWARD_ACTION_ID]=1 << 13
	autoCancelMaskMap[AIR_MOVE_BACKWARD_ACTION_ID]=1 << 14
	autoCancelMaskMap[AIR_DASH_FORWARD_ACTION_ID]=1 << 15
	autoCancelMaskMap[AIR_DASH_BACKWARD_ACTION_ID]=1 << 16
	autoCancelMaskMap[AIR_NEUTRAL_MELEE_ACTION_ID]=1 << 17
	autoCancelMaskMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=1 << 18
	autoCancelMaskMap[AIR_NEUTRAL_TOOL_ACTION_ID]=1 << 19
	autoCancelMaskMap[AIR_DASH_DOWNWARD_ACTION_ID]=1 << 20
	autoCancelMaskMap[AIR_MOVE_STOP_ACTION_ID] = 1 << 21
	autoCancelMaskMap[AIR_AUTO_RIPOST_ACTION_ID]=1 << 22
	autoCancelMaskMap[FORWARD_SPECIAL_ACTION_ID]=1 << 23
	autoCancelMaskMap[DOWNWARD_MELEE_ACTION_ID]=1 << 24
	autoCancelMaskMap[UPWARD_TOOL_ACTION_ID]=1 << 25
	autoCancelMaskMap[DOWNWARD_TOOL_ACTION_ID]=1 << 26
	autoCancelMaskMap[FORWARD_TOOL_ACTION_ID]=1 << 27
	autoCancelMaskMap[BACKWARD_TOOL_ACTION_ID]=1 << 28
	autoCancelMaskMap[UPWARD_SPECIAL_ACTION_ID]=1 << 29
	autoCancelMaskMap[FORWARD_MELEE_ACTION_ID]=1 << 30
	
	autoCancelMaskMap2[DOWNWARD_SPECIAL_ACTION_ID]=1 #bitshift 0
	autoCancelMaskMap2[BACKWARD_MELEE_ACTION_ID]=1 << 1
	autoCancelMaskMap2[UPWARD_MELEE_ACTION_ID]=1 << 2
	autoCancelMaskMap2[GROUND_FORWARD_DASH_ACTION_ID]=1 << 3
	autoCancelMaskMap2[GROUND_BACKWARD_DASH_ACTION_ID]=1 <<4
	autoCancelMaskMap2[AIR_GRAB_ACTION_ID]=1 <<5
	autoCancelMaskMap2[GROUND_GRAB_ACTION_ID]=1 <<6
	autoCancelMaskMap2[PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID]=1 <<7
	autoCancelMaskMap2[PLATFORM_DROP_ACTION_ID]=1 <<8
	autoCancelMaskMap2[PLATFORM_ANIMATION_CANCEL_ACTION_ID]=1 <<9
	autoCancelMaskMap2[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=1 <<10
	autoCancelMaskMap2[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]=1 <<11
	autoCancelMaskMap2[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]=1 <<12
	autoCancelMaskMap2[APEX_ONLY_FAST_FALL_ACTION_ID]=1 <<13
	autoCancelMaskMap2[PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID]=1 <<14
	autoCancelMaskMap2[PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID]=1 <<15
	autoCancelMaskMap2[GROUND_PUSH_BLOCKING_ACTION_ID]=1 <<16 
	autoCancelMaskMap2[AIR_PUSH_BLOCKING_ACTION_ID]=1 <<17
	autoCancelMaskMap2[AIR_JUMP_ACTION_ID]=1 << 18
	autoCancelMaskMap2[AIR_JUMP_FORWARD_ACTION_ID]=1 << 19
	autoCancelMaskMap2[AIR_JUMP_BACKWARD_ACTION_ID]=1 << 20
	autoCancelMaskMap2[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=1 << 21
	autoCancelMaskMap2[BASIC_CROUCH_CANCEL_ACTION_ID]=1 << 22
	autoCancelMaskMap2[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID] = 1 << 23
	autoCancelMaskMap2[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID] = 1 << 24
	autoCancelMaskMap2[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID] = 1 << 25
	
	
		
	customSpamProrationAttackMap[NEUTRAL_MELEE_SPRITE_ANIME_ID]=[
	null, #default meaty hitstun proration
	null,#default basic hitstun proration
	[1,1,1]#NO PRORATION on damage spam
	]
	customSpamProrationAttackMap[BACKWARD_MELEE_SPRITE_ANIME_ID]=[
	null,#meaty hitstunproration	
	[0,-1,-3,-7],#basic hitstunproration
	null,#default damage proration
	]
	

	
	customSpamProrationAttackMap[DOWN_WARD_MELEE_SPRITE_ANIME_ID]=[
	null,#meaty hitstunproration	
	[0,0,-1,-3,-7],#basic hitstunproration
	null,#default damage proration
	]
	
	customSpamProrationAttackMap[FORWARD_MELEE_SPRITE_ANIME_ID]=[
	null,#meaty hitstunproration	
	[0,-1,-3,-7],#basic hitstunproration
	null,#default damage proration
	]
	
	customSpamProrationAttackMap[DOWNWARD_TOOL_SPRITE_ANIME_ID]=[
	 #[1,0.3,0.1], #default hitstun proration
	null,#meaty hitstunproration	
	[0,-23,-40],#basic hitstunproration
	null, #default damage proration
	]

#IT'S a double hit attack, so slow proration by 2
	customSpamProrationAttackMap[UPWARD_MELEE_SPRITE_ANIME_ID]=[	
	[1,1,0.9,0.9,0.75,0.75],
	[0,0,-1,-1,-5,-5,],
	[0.95,0.95,0.9,0.9,0.85,0.85,], 
	]


	customSpamProrationAttackMap[UPWARD_SPECIAL_SPRITE_ANIME_ID]=[	
	[1,0.65,0.35,0.15,0.05],
	null,#[0,0,-1,-1,-5,-5,],
	null,#[0.95,0.95,0.9,0.9,0.85,0.85,], 
	]

	
	
	
	#specify the attacks on ecan hit with one before they change
	addOnTimeHitSpriteAnimationMap(AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID,EXPIRED_AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID)	

#const HIT_THIS_COMBO_IX = 0
#const REMAPPED_SPRITE_ANIMATION_ID_IX=1

		
	#delayed tap action series (REKAS)
	
	#series 1
	#up tool
	delayedTapActionIdLookup[UPWARD_TOOL_ACTION_ID]=UP_TOOL_NORMAL_ACTION_ID
	delayedTapActionIdLookup[UP_TOOL_NORMAL_ACTION_ID]=UP_TOOL_REKA_ACTION_ID
	
	delayedTapActionIdReverseLookup[UP_TOOL_REKA_ACTION_ID]=UP_TOOL_NORMAL_ACTION_ID
	delayedTapActionIdReverseLookup[UP_TOOL_NORMAL_ACTION_ID]=UPWARD_TOOL_ACTION_ID

	#forward tool
	delayedTapActionIdLookup[FORWARD_TOOL_ACTION_ID]=FORWARD_TOOL_NORMAL_ACTION_ID
	delayedTapActionIdLookup[FORWARD_TOOL_NORMAL_ACTION_ID]=FORWARD_TOOL_REKA_ACTION_ID
	
	delayedTapActionIdReverseLookup[FORWARD_TOOL_REKA_ACTION_ID]=FORWARD_TOOL_NORMAL_ACTION_ID
	delayedTapActionIdReverseLookup[FORWARD_TOOL_NORMAL_ACTION_ID]=FORWARD_TOOL_ACTION_ID


	#iterate all actions
	var i = 0
	while i <= LARGEST_ACTION_ID:
		
		#by default actions are the same regardless
		#of if glove has ball of not
		var actionPairRow = []
		actionPairRow.append(i)
		actionPairRow.append(i)
		
		#add the id pair row
		actionIdGroups.append(actionPairRow)
		i = i +1
	

		

	actionIdGroups[DOWNWARD_TOOL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_D_TOOL_ACTION_ID
	actionIdGroups[BACKWARD_SPECIAL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_B_SPECIAL_ACTION_ID
	actionIdGroups[DOWNWARD_SPECIAL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_D_SPECIAL_ACTION_ID
	actionIdGroups[FORWARD_SPECIAL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_F_SPECIAL_ACTION_ID
	actionIdGroups[NEUTRAL_SPECIAL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_N_SPECIAL_ACTION_ID
	actionIdGroups[AIR_NEUTRAL_SPECIAL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_AIR_SPECIAL_ACTION_ID
	actionIdGroups[UPWARD_SPECIAL_ACTION_ID][ANGRY_ANIMATIONS_IX]=ANGRY_U_SPECIAL_ACTION_ID
	

	
	
#toggle the action id group index based on if hase ball	
func setAngryFlag(flag):
	if not flag:
		currentActionIdGroup = CALM_ANIMATIONS_IX
	else:
		currentActionIdGroup = ANGRY_ANIMATIONS_IX



#sub classes can override this to change the aciton id dynamically
#depending on some special state. This function will be called when resolving the
#sprite id and movement id
func actionIdRemapHook(actionId): 
	return _actionIdRemapHook(actionId,currentActionIdGroup)
	
func _actionIdRemapHook(actionId,stanceIx):
	if actionId == null:
		return null
	return actionIdGroups[actionId][stanceIx]
	
func populateCommandAttackMap(inputManager):
	
	#note, make sure the map is consistent with map defined in ready()
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_NEUTRAL_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_DOWNWARD_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_FORWARD_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_BACKWARD_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_UPWARD_MELEE] = true
	
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_NEUTRAL_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_BACKWARD_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_FORWARD_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_UPWARD_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_DOWNWARD_SPECIAL] = true
	
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_NEUTRAL_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_UPWARD_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_BACKWARD_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_FORWARD_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_DOWNWARD_TOOL] = true
	
	
	
func init(playerController):
	.init(playerController)
	
	#set the node paths to dash basic movements so sped can be adjusted
	#forwardAirDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/air-dash-forward/cplx_mvm0/bm0"
	#backwardAirDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/air-dash-backward/cplx_mvm0/bm0"
	#forwardGroundDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/ground-dash-forward/cplx_mvm0/bm0"
	#backwardGroundDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/ground-dash-backward/cplx_mvm0/bm0"
	
#	forwardJumpBM1NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-forward/cplx_mvm0/bm0"
	#backwardJumpBM1NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-backward/cplx_mvm0/bm0"
	#forwardJumpBM2NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-forward/cplx_mvm1/bm0"
	#backwardJumpBM2NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-backward/cplx_mvm1/bm0"
	#neutralJumpBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump/cplx_mvm0/bm0"
	
func reset():
	.reset()
	currentActionIdGroup = CALM_ANIMATIONS_IX