extends "res://ActionAnimationManager.gd"


const gloveBallActionAnimeManagerResource = preload("res://projectiles/GloveBaseBallActionManager.gd")
const JUMP_SPRITE_ANIME_ID = 0
const WALK_FORWARD_SPRITE_ANIME_ID = 1
const GROUND_IDLE_SPRITE_ANIME_ID = 2
const AIR_IDLE_SPRITE_ANIME_ID = 3
const NEUTRAL_MELEE_SPRITE_ANIME_ID = 4

const NEUTRAL_SPECIAL_SPRITE_ANIME_ID = 6
const REBOUND_SPRITE_ANIME_ID = 7
const CROUCH_SPRITE_ANIME_ID = 8
const NEUTRAL_TOOL_SPRITE_ANIME_ID = 9
const AUTO_RIPOST_SPRITE_ANIME_ID = 10
const AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID = 11
const AIR_DASH_SPRITE_ANIME_ID = 12
const RIPOST_SPRITE_ANIME_ID = 13
const NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID = 14
const AIR_MOVE_SPRITE_ANIME_ID = 15
const AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID = 16
const AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID = 17
const OLD_FORWARD_SPECIAL_SPRITE_ANIME_ID = 18
const LANDING_LAG_SPRITE_ANIME_ID = 19
const WALK_BACKWARD_SPRITE_ANIME_ID = 20
const DOWN_WARD_MELEE_SPRITE_ANIME_ID = 21
const FORWARD_SPECIAL_SPRITE_ANIME_ID = 22
const UPWARD_TOOL_SPRITE_ANIME_ID = 23
const LANDING_HITSTUN_SPRITE_ANIME_ID = 24
const INVULNERABLE_HITSTUN_AIR_SPRITE_ANIME_ID = 25
const BACKWARD_TOOL_SPRITE_ANIME_ID = 26
const FORWARD_MELEE_SPRITE_ANIME_ID = 27
const GROUND_FORWARD_DASH_SPRITE_ANIME_ID = 28
const GROUND_BACKWARD_DASH_SPRITE_ANIME_ID = 29
const DOWNWARD_TOOL_SPRITE_ANIME_ID = 30
const UPWARD_SPECIAL_SPRITE_ANIME_ID = 31
const DOWNWARD_SPECIAL_SPRITE_ANIME_ID = 32
const AIR_HITSTUN_SPRITE_ANIME_ID = 33
const BACK_MELEE_SPRITE_ANIME_ID = 34
const UPWARD_MELEE_SPRITE_ANIME_ID = 35
const GROUND_GRAB_SPRITE_ANIME_ID = 36
const FORWARD_TOOL_SPRITE_ANIME_ID = 37
const NO_BALL_GROUND_IDLE_SPRITE_ANIME_ID = 38
const NO_BALL_AIR_TOOL_SPRITE_ANIME_ID = 39
const NO_BALL_NEUTRAL_TOOL_SPRITE_ANIME_ID = 40
const NO_BALL_FORWARD_TOOL_SPRITE_ANIME_ID = 41
const NO_BALL_DOWNWARD_TOOL_SPRITE_ANIME_ID = 42
const NO_BALL_BACKWARD_TOOL_SPRITE_ANIME_ID = 43
const NO_BALL_UPWARD_TOOL_SPRITE_ANIME_ID = 44
const NO_BALL_BLOCK_SPRITE_ANIME_ID = 45
#const ON_HIT_GROUND_GRAB_SPRITE_ANIME_ID = 46#unused
const GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID = 47
const FORWARD_ROLLING_TECH_SPRITE_ANIME_ID = 48
const BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID = 49
const CEILING_TECH_SPRITE_ANIME_ID = 50
const WALL_TECH_SPRITE_ANIME_ID = 51
const BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID = 52
const PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID = 53
const CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID = 54
const PLATFORM_DROP_SPRITE_ANIME_ID = 55
const UNCROUCH_SPRITE_ANIME_ID = 56
const ON_HIT_GROUND_GRAB_SPRITE_ANIME_ID = 57
const GROUND_DASH_CANCEL_RECOVERY_SPRITE_ANIME_ID = 58
const PUSH_BLOCK_SPRITE_ANIME_ID = 59
const GROUND_GRAB_THROW_SPRITE_ANIME_ID = 60
const AIR_GRAB_THROW_SPRITE_ANIME_ID = GROUND_GRAB_THROW_SPRITE_ANIME_ID #same for now
const AIR_GRAB_SPRITE_ANIME_ID = 61
const ON_HIT_AIR_GRAB_SPRITE_ANIME_ID = 62
const NON_CROUCH_CANCELABLED_F_GROUND_DASH_SPRITE_ANIME_ID=63
const NON_CROUCH_CANCELABLED_B_GROUND_DASH_SPRITE_ANIME_ID=64
const PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID=65
const PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_SPRITE_ANIME_ID=66
const NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID=67
const NEW_AIR_SPECIAL_P2_SPRITE_ANIME_ID=68
const NEW_AIR_SPECIAL_P3_SPRITE_ANIME_ID=69
const NEW_B_MELEE_SPRITE_ANIME_ID=70
const STUNNED_SPRITE_ANIME_ID=71
const AIR_JUMP_SPRITE_ANIME_ID=72
const BASIC_CROUCH_CANCEL_SPRITE_ANIME_ID=73
const NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID=74
const INVULNERABLE_GUARD_BREAK_SPRITE_ANIME_ID=75
const AIR_DASH_BACK_SPRITE_ANIME_ID = 76
const NEW_BACK_SPECIAL_SPRITE_ANIME_ID = 77
const GROUND_GRAB_FORWARD_THROW_SPRITE_ANIME_ID=78
const GROUND_GRAB_FORWARD_DOWN_THROW_SPRITE_ANIME_ID=79
const GROUND_GRAB_DOWN_THROW_SPRITE_ANIME_ID=80
const GROUND_GRAB_BACKWARD_DOWN_THROW_SPRITE_ANIME_ID=81
const GROUND_GRAB_BACKWARD_THROW_SPRITE_ANIME_ID=82
const GROUND_GRAB_BACKWARD_UP_THROW_SPRITE_ANIME_ID=83
const GROUND_GRAB_UP_THROW_SPRITE_ANIME_ID=84
const GROUND_GRAB_FORWARD_UP_THROW_SPRITE_ANIME_ID=85

const NO_BALL_WALK_BACK_SPRITE_ANIME_ID=86
const  NO_BALL_WALK_FORWARD_SPRITE_ANIME_ID=87
#Movement animation ids
const JUMP_MVM_ANIME_ID = 0
const AIR_MOVE_FORWARD_MVM_ANIME_ID = 1
const GROUND_MOVE_FORWARD_MVM_ANIME_ID = 2
const GROUND_MOVE_BACKWARD_MVM_ANIME_ID = 3
const AIR_MOVE_BACKWARD_MVM_ANIME_ID = 4
const AIR_IDLE_MVM_ANIME_ID = 5
const AIR_DASH_FORWARD_MVM_ANIME_ID = 6
const AIR_DASH_BACKWARD_MVM_ANIME_ID = 7
const GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID = 8
const NEUTRAL_MELEE_MVM_ANIME_ID = 9
const NEUTRAL_SPECIAL_MVM_ANIME_ID = 10
const REBOUND_MVM_ANIME_ID = 11
const JUMP_FORWARD_MVM_ANIME_ID = 12
const JUMP_BACKWARD_MVM_ANIME_ID = 13
const AIR_DASH_DOWNWARD_MVM_ANIME_ID = 14
const RIPOST_MVM_ANIME_ID = 15
const AIR_MOVE_STOP_MVM_ANIME_ID = 16
const OLD_BACK_SPECIAL_MVM_ANIME_ID = 17
const FORWARD_SPECIAL_MVM_ANIME_ID = 18
const WALL_BOUNCE_MVM_ANIME_ID = 19
const INVULNERABLE_HITSTUN_AIR_MVM_ANIME_ID = 20
const BACKWARD_TOOL_MVM_ANIME_ID = 21
const FORWARD_MELEE_MVM_ANIME_ID = 22
const GROUND_FORWARD_DASH_MVM_ANIME_ID = 23
const GROUND_BACKWARD_DASH_MVM_ANIME_ID = 24
const UPWARD_MELEE_MVM_ANIME_ID = 25
const AIR_SPECIAL_MVM_ANIME_ID = 26
const CEILING_TECH_MVM_ANIME_ID = 27
const WALL_TECH_MVM_ANIME_ID = 28
const GROUND_IN_PLACE_TECH_MVM_ANIME_ID = 29
const LAND_ON_PLATFROM_MVM_ANIME_ID = 30
const LEAVE_PLATFROM_HALT_MVM_ANIME_ID = 31
const AIR_HITSTUN_BREAK_FREE_MVM_ANIME_ID = 32
const TECH_ROLL_FORWARD_MVM_ANIME_ID = 33
const TECH_ROLL_BACKWARD_MVM_ANIME_ID = 34

const STOP_PLATFORM_LEAVE_MOMENTUM_MVM_ANIME_ID  = 35
const PLATFORM_DROP_MVM_ANIME_ID  = 36
const GROUND_GRAB_MVM_ANIME_ID = 37
const ON_HIT_GROUND_GRAB_MVM_ANIME_ID = 38
const AIR_BLOCK_STUN_MVM_ANIME_ID = 39
const PUSH_BLOCK_MVM_ANIME_ID = 40
const GROUND_GRAB_UP_THROW_MVM_ANIME_ID = 41
const GROUND_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID = 42
const GROUND_GRAB_FORWARD_THROW_MVM_ANIME_ID = 43
const GROUND_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID = 44
const GROUND_GRAB_DOWN_THROW_MVM_ANIME_ID = 45
const GROUND_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID = 46
const GROUND_GRAB_BACKWARD_THROW_MVM_ANIME_ID = 47
const GROUND_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID = 48
const AIR_GRAB_UP_THROW_MVM_ANIME_ID = 49
const AIR_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID = 50
const AIR_GRAB_FORWARD_THROW_MVM_ANIME_ID = 51
const AIR_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID = 52
const AIR_GRAB_DOWN_THROW_MVM_ANIME_ID = 53
const AIR_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID = 54
const AIR_GRAB_BACKWARD_THROW_MVM_ANIME_ID = 55
const AIR_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID = 56
const AIR_GRAB_MVM_ANIME_ID = 57
const ON_HIT_AIR_GRAB_MVM_ANIME_ID = 58
const AIR_TOOL_MVM_ANIME_ID = 59
const NEW_AIR_SPECIAL_P1_ON_HIT_MVM_ANIME_ID = 60
const NEW_AIR_SPECIAL_P2_ON_HIT_MVM_ANIME_ID = 61
const NEW_AIR_SPECIAL_P3_ON_HIT_MVM_ANIME_ID = 62
const NEW_AIR_SPECIAL_MVM_ANIME_ID = 63
const ZERO_AIR_MVM_ANIME_ID = 64
const AIR_SPECIAL_P3_MVM_ANIME_ID = 65
const STUNNED_MVM_ANIME_ID = 66
const PERFECT_MVM_ANIME_ID = 67
const REBOUND_CLASH_BREAK_MVM_ANIME_ID = 68
const NON_MVM_PUSH_BLOCKING_MVM_ANIME_ID = 69
const MOMENTUM_STOP_MVM_ANIME_ID = 70
const AIR_SPECIAL_P2_MVM_ANIME_ID = 71
const CORNER_HITTING_PUSH_AWAY_MVM_ANIME_ID = 72
const GROUND_TECH_BOUNCE_UP_MVM_ANIME_ID = 73
const WALL_TECH_BOUNCE_UP_MVM_ANIME_ID = 74
const WALL_TECH_BOUNCE_DOWN_MVM_ANIME_ID = 75
const CEILING_BOUNCE_BACK_TECH_MVM_ANIME_ID =76
const CEILING_BOUNCE_FORWARD_TECH_MVM_ANIME_ID = 77
const AIR_TECH_IN_PLACE_MVM_ANIME_ID = 78
const REBOUND_CLASH_BREAK_VICTIM_MVM_ANIME_ID = 79
const F_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID = 80
const B_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID = 81
const BREAK_FROM_HITSTUN_HALT_MVM_ANIME_ID = 82
const AIR_TOOL_NO_BALL_MVM_ANIME_ID = 83
const OKI_MOMENTUM_STOP_MVM_ANIME_ID = 84
const PROXIMITY_GUARD_STOP_MVM_ANIME_ID = 85
const ON_HIT_AIR_SPECIAL_REKA1_HIT_MVM_STOP_MVM_ANIME_ID =86
const LANDING_LAG_MVM_ANIME_ID = 87
const INVULNERABLE_GUARD_BREAK_MVM_ANIME_ID = 88
const GRAB_CANCEL_MOMENTUM_STOP_MVM_ANIME_ID = 89
const AIR_KEEP_MOMENTUM_MVM_ANIME_ID =90
const NEW_BACK_SPECIAL_MVM_ANIME_ID=91
const GROUND_GRAB_NEUTRAL_THROW_MVM_ANIME_ID=92
const AIR_GRAB_NEUTRAL_THROW_MVM_ANIME_ID = 93
const GETTING_PUSH_BLOCKED_IN_NEUTRAL_MVM_ANIME_ID=94
#action  animation ids
const JUMP_ACTION_ID = 0
const AIR_MOVE_FORWARD_ACTION_ID = 1
const GROUND_MOVE_FORWARD_ACTION_ID = 2
const GROUND_MOVE_BACKWARD_ACTION_ID = 3
const AIR_MOVE_BACKWARD_ACTION_ID = 4
const AIR_IDLE_ACTION_ID = 5
const AIR_DASH_FORWARD_ACTION_ID = 6
const AIR_DASH_BACKWARD_ACTION_ID = 7
const GROUND_IDLE_ACTION_ID = 8
const NEUTRAL_MELEE_ACTION_ID = 9
const FORWARD_MELEE_ACTION_ID = 39
const BACKWARD_MELEE_ACTION_ID = 46
const DOWNWARD_MELEE_ACTION_ID = 32
const UPWARD_MELEE_ACTION_ID = 47
const NEUTRAL_SPECIAL_ACTION_ID = 10
const FORWARD_SPECIAL_ACTION_ID = 33 
const BACKWARD_SPECIAL_ACTION_ID = 27 
const DOWNWARD_SPECIAL_ACTION_ID = 44
const UPWARD_SPECIAL_ACTION_ID = 43 
const REBOUND_ACTION_ID = 11
const CROUCH_ACTION_ID = 12
const AIR_NEUTRAL_MELEE_ACTION_ID = 13
const AIR_NEUTRAL_SPECIAL_ACTION_ID = 14
const JUMP_FORWARD_ACTION_ID = 15
const JUMP_BACKWARD_ACTION_ID = 16
const AIR_DASH_DOWNWARD_ACTION_ID = 17
const AIR_NEUTRAL_TOOL_ACTION_ID = 18
const NEUTRAL_TOOL_ACTION_ID = 19
const FORWARD_TOOL_ACTION_ID = 49 
const BACKWARD_TOOL_ACTION_ID = 38
const DOWNWARD_TOOL_ACTION_ID = 42 
const UPWARD_TOOL_ACTION_ID = 34 

const PAUSE_PLAYER_ACTION_ID = 21
const GROUND_RIPOST_ACTION_ID = 22
const AIR_RIPOST_ACTION_ID = 23
const AUTO_RIPOST_ACTION_ID = 24
const AUTO_RIPOST_ON_HIT_ACTION_ID = 25
const AIR_MOVE_STOP_ACTION_ID = 26
#const BACKWARD_SPECIAL_ACTION_ID = 27
const AIR_AUTO_RIPOST_ACTION_ID = 28
const AIR_AUTO_RIPOST_ON_HIT_ACTION_ID = 29
const LANDING_STOP_MOMENTUM_ACTION_ID = 30
const LANDING_LAG_ACTION_ID = 31

const WALL_BOUNCE_ACTION_ID = 36

const GROUND_FORWARD_DASH_ACTION_ID = 40
const GROUND_BACKWARD_DASH_ACTION_ID = 41
const GROUND_GRAB_ACTION_ID = 48
const AIR_GRAB_ACTION_ID = 74 #AIR anti-block

const NO_BALL_GROUND_IDLE_ACTION_ID = 50
const NO_BALL_AIR_TOOL_ACTION_ID = 51
const NO_BALL_NEUTRAL_TOOL_ACTION_ID = 52 # no action, glove loses this action with no ball
const NO_BALL_FORWARD_TOOL_ACTION_ID = 53 # no action, glove loses this action with no ball
const NO_BALL_DOWNWARD_TOOL_ACTION_ID = 54 # no action, glove loses this action with no ball
const NO_BALL_BACKWARD_TOOL_ACTION_ID = 55
const NO_BALL_UPWARD_TOOL_ACTION_ID = 56
const NO_BALL_BLOCK_ACTION_ID = 57
#const ON_HIT_GROUND_GRAB_ACTION_ID = 58


const GROUND_IN_PLACE_TECH_ACTION_ID = 59
const ROLLING_FORWARD_TECH_ACTION_ID = 60
const ROLLING_BACKWARD_TECH_ACTION_ID = 61
const CEILING_TECH_ACTION_ID = 62
const WALL_TECH_ACTION_ID = 63


const BUDGET_BLOCK_HIT_LAG_ACTION_ID = 64
const PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID = 65
const CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID = 66


const LEAVE_PLATFROM_HALT_ACTION_ID = 67
const LAND_ON_PLATFROM_ACTION_ID=68
const AIR_HITSTUN_BREAK_FREE_ACTION_ID = 69
const STOP_PLATFORM_LEAVE_MOMENTUM_ACTION_ID = 70

const PLATFORM_DROP_ACTION_ID = 71
const PLATFORM_ANIMATION_CANCEL_ACTION_ID = 72
const UNCROUCH_ACTION_ID = 73
const ON_HIT_GROUND_GRAB_ACTION_ID = 58
const FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID = 75
const AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID = 76
const GETTING_PUSH_BLOCKED_ACTION_ID = 77
const GROUND_PUSH_BLOCKING_ACTION_ID = 78



const GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID = 79
const GROUND_GRAB_FORWARD_THROW_ACTION_ID = 80
const GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID = 81
const GROUND_GRAB_DOWN_THROW_ACTION_ID = 82
const GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID = 83
const GROUND_GRAB_BACKWARD_THROW_ACTION_ID = 84
const GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID = 85

const ON_HIT_AIR_GRAB_ACTION_ID = 86


const AIR_GRAB_UP_THROW_ACTION_ID = 87
const AIR_GRAB_FORWARD_UP_THROW_ACTION_ID = 88
const AIR_GRAB_FORWARD_THROW_ACTION_ID = 89
const AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID = 90
const AIR_GRAB_DOWN_THROW_ACTION_ID = 91
const AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID = 92
const AIR_GRAB_BACKWARD_THROW_ACTION_ID = 93
const AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID = 94

const GROUND_GRAB_UP_THROW_ACTION_ID = 95

const APEX_ONLY_FAST_FALL_ACTION_ID = 96
const NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID = 97
const NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID = 98
const PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID=99
const PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID=100

const NO_BALL_AIR_AUTO_RIPOST_ACTION_ID = 101

const NEW_AIR_SPECIAL_P1_ACTION_ID = 102
const NEW_AIR_SPECIAL_P2_ACTION_ID = 103
const NEW_AIR_SPECIAL_P3_ACTION_ID = 104

const NEW_AIR_SPECIAL_ON_HIT_P1_ACTION_ID = 105
const NEW_AIR_SPECIAL_ON_HIT_P2_ACTION_ID = 106
const NEW_AIR_SPECIAL_ON_HIT_P3_ACTION_ID = 107

const STUNNED_ACTION_ID=108

const PERFECT_MOMENTUM_STOP_BLOCK_ACTION_ID=109
const REBOUND_CLASH_BREAK_ACTION_ID=110
const AIR_PUSH_BLOCKING_ACTION_ID = 111

const AIR_JUMP_ACTION_ID = 112
const AIR_JUMP_FORWARD_ACTION_ID = 113
const AIR_JUMP_BACKWARD_ACTION_ID = 114

const MOMENTUM_STOP_ACTION_ID=115
const CORNER_HITTING_PUSH_AWAY_ACTION_ID = 116


const GROUND_BOUNCE_UP_TECH_ACTION_ID = 117
	

const WALL_BOUNCE_UP_TECH_ACTION_ID=118
const WALL_BOUNCE_DOWN_TECH_ACTION_ID=119
const WALL_BOUNCE_AWAY_TECH_ACTION_ID=120
	
const CEILING_BOUNCE_DOWN_TECH_ACTION_ID=121
const CEILING_BOUNCE_FORWARD_TECH_ACTION_ID=122
const CEILING_BOUNCE_BACK_TECH_ACTION_ID=123
const REBOUND_CLASH_BREAK_VICTIM_ACTION_ID=124

const BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID=125
const BASIC_CROUCH_CANCEL_ACTION_ID=126
const BREAK_FROM_HITSTUN_HALT_ACTION_ID=127
const NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID=128
const NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID=129
const NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID=130
const SLIDING_GROUND_IDLE_ACTION_ID = 131
const ON_HIT_AIR_SPECIAL_REKA1_HIT_MVM_STOP_ACTION_ID=132
const INVULNERABLE_GUARD_BREAK_ACTION_ID = 133
const GRAB_CANCEL_MOMENTUM_STOP_ACTION_ID = 134
const SLIDING_AIR_IDLE_ACTION_ID = 135
const GROUND_GRAB_NEUTRAL_THROW_ACTION_ID=136
const AIR_GRAB_NEUTRAL_THROW_ACTION_ID = 137
const GETTING_PUSH_BLOCKED_IN_NEUTRAL_ACTION_ID = 138
const NO_BALL_WALK_BACK_ACTION_ID = 139
const NO_BALL_WALK_FORWARD_ACTION_ID = 140
const LARGEST_ACTION_ID = 140


#const FORWARD_SPECIAL_ACTION_ID = -1
#const DOWNWARD_MELEE_ACTION_ID = -1

const WITH_BALL_ANIMATIONS_IX = 0
const NO_BALL_ANIMATIONS_IX = 1


var currentActionIdGroup = WITH_BALL_ANIMATIONS_IX
#2D ARRAY that holds the action id pairs of with ball vs has no ball
#column 0 is action id when glove has ball
#column 1 is action id when glove doesn't have ball
#row i is starnd actionId = i
#animations that aren't different with and without ball are idential in a row

var actionIdGroups = []

func _ready():
	LANDING_HITSTUN_ACTION_ID = 35
	INVULNERABLE_AIR_HITSTUN_ACTION_ID = 37
	AIR_HITSTUN_ACTION_ID=45
	attackMaps[MELEE_IX][NEUTRAL_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][DOWN_WARD_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][FORWARD_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][NEW_B_MELEE_SPRITE_ANIME_ID] = true
	attackMaps[MELEE_IX][UPWARD_MELEE_SPRITE_ANIME_ID] = true
	
	attackMaps[SPECIAL_IX][NEUTRAL_SPECIAL_SPRITE_ANIME_ID] = true
	#attackMaps[SPECIAL_IX][BACK_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][NEW_BACK_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][FORWARD_SPECIAL_SPRITE_ANIME_ID] = true
	#attackMaps[SPECIAL_IX][AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID] = true
	#attackMaps[SPECIAL_IX][AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][DOWNWARD_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][UPWARD_SPECIAL_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][NEW_AIR_SPECIAL_P2_SPRITE_ANIME_ID] = true
	attackMaps[SPECIAL_IX][NEW_AIR_SPECIAL_P3_SPRITE_ANIME_ID] = true

	
	attackMaps[TOOL_IX][NEUTRAL_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][UPWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][BACKWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][DOWNWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][FORWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NO_BALL_NEUTRAL_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NO_BALL_AIR_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NO_BALL_UPWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NO_BALL_BACKWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NO_BALL_DOWNWARD_TOOL_SPRITE_ANIME_ID] = true
	attackMaps[TOOL_IX][NO_BALL_FORWARD_TOOL_SPRITE_ANIME_ID] = true
	
	#the special effects attack type map is same as attack map in gloves's case
	visualSFXAttackMap=attackMaps
	audioSFXAttackMap=attackMaps
	
	
	
	animationLookup[SPRITE_ANIME_IX][JUMP_ACTION_ID]=JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_JUMP_ACTION_ID]=AIR_JUMP_SPRITE_ANIME_ID	
	#animationLookup[SPRITE_ANIME_IX][AIR_MOVE_FORWARD_ACTION_ID]=AIR_MOVE_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][AIR_MOVE_BACKWARD_ACTION_ID]=AIR_MOVE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_MOVE_FORWARD_ACTION_ID]=null
	animationLookup[SPRITE_ANIME_IX][AIR_MOVE_BACKWARD_ACTION_ID]=null
	animationLookup[SPRITE_ANIME_IX][AIR_IDLE_ACTION_ID]=AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_MOVE_FORWARD_ACTION_ID]=WALK_FORWARD_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_MOVE_BACKWARD_ACTION_ID]=WALK_BACKWARD_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_IDLE_ACTION_ID]=GROUND_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][SLIDING_GROUND_IDLE_ACTION_ID]=GROUND_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][SLIDING_AIR_IDLE_ACTION_ID]=AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_DASH_FORWARD_ACTION_ID]=AIR_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_DASH_BACKWARD_ACTION_ID]=AIR_DASH_BACK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_MELEE_ACTION_ID]=NEUTRAL_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_MELEE_ACTION_ID]=NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_SPECIAL_ACTION_ID]=NEUTRAL_SPECIAL_SPRITE_ANIME_ID#
	#animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_SPECIAL_ACTION_ID]=AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_SPECIAL_ACTION_ID]=NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][REBOUND_ACTION_ID]=REBOUND_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][REBOUND_CLASH_BREAK_VICTIM_ACTION_ID]=REBOUND_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][CROUCH_ACTION_ID]=CROUCH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][JUMP_FORWARD_ACTION_ID]=JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][JUMP_BACKWARD_ACTION_ID]=JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_JUMP_FORWARD_ACTION_ID]=AIR_JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_JUMP_BACKWARD_ACTION_ID]=AIR_JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_DASH_DOWNWARD_ACTION_ID]=null
	animationLookup[SPRITE_ANIME_IX][AIR_NEUTRAL_TOOL_ACTION_ID]=AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEUTRAL_TOOL_ACTION_ID]=NEUTRAL_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_RIPOST_ACTION_ID]=RIPOST_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][GROUND_RIPOST_ACTION_ID]=RIPOST_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AUTO_RIPOST_ACTION_ID]=AUTO_RIPOST_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_AUTO_RIPOST_ACTION_ID]=AUTO_RIPOST_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AUTO_RIPOST_ON_HIT_ACTION_ID]=AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_AUTO_RIPOST_ON_HIT_ACTION_ID]=AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][HITSTUN_ACTION_ID] = HITSTUN_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][AIR_MOVE_STOP_ACTION_ID] = AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_MOVE_STOP_ACTION_ID] = null
	#animationLookup[SPRITE_ANIME_IX][BACKWARD_SPECIAL_ACTION_ID] = BACK_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BACKWARD_SPECIAL_ACTION_ID] = NEW_BACK_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][LANDING_STOP_MOMENTUM_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][LANDING_LAG_ACTION_ID] = LANDING_LAG_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][DOWNWARD_MELEE_ACTION_ID] = DOWN_WARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_SPECIAL_ACTION_ID] = FORWARD_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UPWARD_TOOL_ACTION_ID] = UPWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][LANDING_HITSTUN_ACTION_ID] = LANDING_HITSTUN_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][INVULNERABLE_AIR_HITSTUN_ACTION_ID] = INVULNERABLE_HITSTUN_AIR_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BACKWARD_TOOL_ACTION_ID] = BACKWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][DOWNWARD_TOOL_ACTION_ID] = DOWNWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_MELEE_ACTION_ID] = FORWARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_FORWARD_DASH_ACTION_ID] = GROUND_FORWARD_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_BACKWARD_DASH_ACTION_ID] = GROUND_BACKWARD_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_ACTION_ID] = GROUND_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_ACTION_ID] = AIR_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][DOWNWARD_SPECIAL_ACTION_ID] = DOWNWARD_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UPWARD_SPECIAL_ACTION_ID] = UPWARD_SPECIAL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_HITSTUN_ACTION_ID] = AIR_HITSTUN_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][BACKWARD_MELEE_ACTION_ID] = BACK_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BACKWARD_MELEE_ACTION_ID] = NEW_B_MELEE_SPRITE_ANIME_ID
	
	animationLookup[SPRITE_ANIME_IX][UPWARD_MELEE_ACTION_ID] = UPWARD_MELEE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_TOOL_ACTION_ID] = FORWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ON_HIT_GROUND_GRAB_ACTION_ID] = ON_HIT_GROUND_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ON_HIT_AIR_GRAB_ACTION_ID] = ON_HIT_AIR_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_IN_PLACE_TECH_ACTION_ID] = GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_BOUNCE_UP_TECH_ACTION_ID] = GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ROLLING_BACKWARD_TECH_ACTION_ID] = BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][ROLLING_FORWARD_TECH_ACTION_ID] = FORWARD_ROLLING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_BOUNCE_BACK_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_BOUNCE_FORWARD_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CEILING_BOUNCE_DOWN_TECH_ACTION_ID] = CEILING_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_UP_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_DOWN_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][WALL_BOUNCE_AWAY_TECH_ACTION_ID] = WALL_TECH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BUDGET_BLOCK_HIT_LAG_ACTION_ID] = BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][LEAVE_PLATFROM_HALT_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][LAND_ON_PLATFROM_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][AIR_HITSTUN_BREAK_FREE_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][STOP_PLATFORM_LEAVE_MOMENTUM_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][PLATFORM_DROP_ACTION_ID] = PLATFORM_DROP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PLATFORM_ANIMATION_CANCEL_ACTION_ID] = AIR_IDLE_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][UNCROUCH_ACTION_ID] = UNCROUCH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = GROUND_DASH_CANCEL_RECOVERY_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][GETTING_PUSH_BLOCKED_ACTION_ID] = PUSH_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GETTING_PUSH_BLOCKED_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][GROUND_PUSH_BLOCKING_ACTION_ID] = PUSH_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_PUSH_BLOCKING_ACTION_ID] = PUSH_BLOCK_SPRITE_ANIME_ID	
	
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_DOWN_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_DOWN_THROW_ACTION_ID] = GROUND_GRAB_DOWN_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_DOWN_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_UP_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_UP_THROW_ACTION_ID] = GROUND_GRAB_UP_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_UP_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_NEUTRAL_THROW_ACTION_ID] = GROUND_GRAB_THROW_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_UP_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_UP_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_FORWARD_UP_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_FORWARD_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_DOWN_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_DOWN_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_BACKWARD_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID]
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID] 	
	animationLookup[SPRITE_ANIME_IX][AIR_GRAB_NEUTRAL_THROW_ACTION_ID] = animationLookup[SPRITE_ANIME_IX][GROUND_GRAB_NEUTRAL_THROW_ACTION_ID]	
	
	animationLookup[SPRITE_ANIME_IX][NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID] = NON_CROUCH_CANCELABLED_F_GROUND_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID] = NON_CROUCH_CANCELABLED_B_GROUND_DASH_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][APEX_ONLY_FAST_FALL_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEW_AIR_SPECIAL_P1_ACTION_ID] = NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEW_AIR_SPECIAL_P2_ACTION_ID] = NEW_AIR_SPECIAL_P2_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEW_AIR_SPECIAL_P3_ACTION_ID] = NEW_AIR_SPECIAL_P3_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NEW_AIR_SPECIAL_ON_HIT_P1_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][NEW_AIR_SPECIAL_ON_HIT_P2_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][NEW_AIR_SPECIAL_ON_HIT_P3_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][STUNNED_ACTION_ID] = STUNNED_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][PERFECT_MOMENTUM_STOP_BLOCK_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][REBOUND_CLASH_BREAK_ACTION_ID] = REBOUND_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][MOMENTUM_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][BASIC_CROUCH_CANCEL_ACTION_ID] = BASIC_CROUCH_CANCEL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][BREAK_FROM_HITSTUN_HALT_ACTION_ID] = null	
	animationLookup[SPRITE_ANIME_IX][NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID] = NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID] = NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID] = NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID	
	animationLookup[SPRITE_ANIME_IX][ON_HIT_AIR_SPECIAL_REKA1_HIT_MVM_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][GRAB_CANCEL_MOMENTUM_STOP_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][GETTING_PUSH_BLOCKED_IN_NEUTRAL_ACTION_ID] = null
	

	animationLookup[SPRITE_ANIME_IX][NO_BALL_GROUND_IDLE_ACTION_ID] = NO_BALL_GROUND_IDLE_SPRITE_ANIME_ID #needs to be updated
	animationLookup[SPRITE_ANIME_IX][NO_BALL_AIR_TOOL_ACTION_ID] = NO_BALL_AIR_TOOL_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][NO_BALL_NEUTRAL_TOOL_ACTION_ID] = NO_BALL_NEUTRAL_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NO_BALL_NEUTRAL_TOOL_ACTION_ID] = null
	#animationLookup[SPRITE_ANIME_IX][NO_BALL_FORWARD_TOOL_ACTION_ID] = NO_BALL_FORWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NO_BALL_FORWARD_TOOL_ACTION_ID] = null
	#animationLookup[SPRITE_ANIME_IX][NO_BALL_DOWNWARD_TOOL_ACTION_ID] = NO_BALL_DOWNWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NO_BALL_DOWNWARD_TOOL_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][NO_BALL_BACKWARD_TOOL_ACTION_ID] = NO_BALL_BACKWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NO_BALL_UPWARD_TOOL_ACTION_ID] = NO_BALL_UPWARD_TOOL_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][NO_BALL_BLOCK_ACTION_ID] = AUTO_RIPOST_SPRITE_ANIME_ID 
	animationLookup[SPRITE_ANIME_IX][NO_BALL_AIR_AUTO_RIPOST_ACTION_ID] = AUTO_RIPOST_SPRITE_ANIME_ID 
	animationLookup[SPRITE_ANIME_IX][NO_BALL_WALK_BACK_ACTION_ID] = NO_BALL_WALK_BACK_SPRITE_ANIME_ID 
	animationLookup[SPRITE_ANIME_IX][NO_BALL_WALK_FORWARD_ACTION_ID] = NO_BALL_WALK_FORWARD_SPRITE_ANIME_ID 


	
	animationLookup[SPRITE_ANIME_IX][CORNER_HITTING_PUSH_AWAY_ACTION_ID] = null
	animationLookup[SPRITE_ANIME_IX][BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = GROUND_DASH_CANCEL_RECOVERY_SPRITE_ANIME_ID
	#animationLookup[SPRITE_ANIME_IX][ON_HIT_GROUND_GRAB_ACTION_ID] = ON_HIT_GROUND_GRAB_SPRITE_ANIME_ID
	animationLookup[SPRITE_ANIME_IX][INVULNERABLE_GUARD_BREAK_ACTION_ID] = INVULNERABLE_GUARD_BREAK_SPRITE_ANIME_ID
	
	
	animationLookup[MVM_ANIME_IX][JUMP_ACTION_ID]=JUMP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_JUMP_ACTION_ID]=JUMP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][AIR_MOVE_FORWARD_ACTION_ID]=AIR_MOVE_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_MOVE_BACKWARD_ACTION_ID]=AIR_MOVE_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_IDLE_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID #no movement assosiated
	animationLookup[MVM_ANIME_IX][GROUND_MOVE_FORWARD_ACTION_ID]=GROUND_MOVE_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_MOVE_BACKWARD_ACTION_ID]=GROUND_MOVE_BACKWARD_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][GROUND_IDLE_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][SLIDING_GROUND_IDLE_ACTION_ID]=GROUND_SLOW_DOWN_SLIDE_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][SLIDING_AIR_IDLE_ACTION_ID]=AIR_KEEP_MOMENTUM_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][AIR_DASH_FORWARD_ACTION_ID]=AIR_DASH_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_DASH_BACKWARD_ACTION_ID]=AIR_DASH_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_MELEE_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_MELEE_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_SPECIAL_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_SPECIAL_ACTION_ID]=AIR_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_SPECIAL_ACTION_ID]=NEW_AIR_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][REBOUND_ACTION_ID]=REBOUND_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][REBOUND_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][REBOUND_CLASH_BREAK_VICTIM_ACTION_ID]=REBOUND_CLASH_BREAK_VICTIM_MVM_ANIME_ID	
	#animationLookup[MVM_ANIME_IX][REBOUND_CLASH_BREAK_VICTIM_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID		
	animationLookup[MVM_ANIME_IX][CROUCH_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][JUMP_FORWARD_ACTION_ID]=JUMP_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][JUMP_BACKWARD_ACTION_ID]=JUMP_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_JUMP_FORWARD_ACTION_ID]=JUMP_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_JUMP_BACKWARD_ACTION_ID]=JUMP_BACKWARD_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][AIR_DASH_DOWNWARD_ACTION_ID]=AIR_DASH_DOWNWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_NEUTRAL_TOOL_ACTION_ID]=AIR_TOOL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEUTRAL_TOOL_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_RIPOST_ACTION_ID]=RIPOST_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][GROUND_RIPOST_ACTION_ID]=RIPOST_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AUTO_RIPOST_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_AUTO_RIPOST_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AUTO_RIPOST_ON_HIT_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_AUTO_RIPOST_ON_HIT_ACTION_ID]=ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][HITSTUN_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][AIR_MOVE_STOP_ACTION_ID] = AIR_MOVE_STOP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][BACKWARD_SPECIAL_ACTION_ID] = BACK_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACKWARD_SPECIAL_ACTION_ID] = NEW_BACK_SPECIAL_MVM_ANIME_ID
	
	#animationLookup[MVM_ANIME_IX][LANDING_STOP_MOMENTUM_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LANDING_STOP_MOMENTUM_ACTION_ID]=LANDING_LAG_MVM_ANIME_ID 
	#animationLookup[MVM_ANIME_IX][LANDING_LAG_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LANDING_LAG_ACTION_ID]=LANDING_LAG_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_MELEE_ACTION_ID]=MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_SPECIAL_ACTION_ID]=FORWARD_SPECIAL_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][UPWARD_TOOL_ACTION_ID] = BACK_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UPWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LANDING_HITSTUN_ACTION_ID]=OKI_MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_ACTION_ID]=WALL_BOUNCE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][INVULNERABLE_AIR_HITSTUN_ACTION_ID] = INVULNERABLE_HITSTUN_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACKWARD_TOOL_ACTION_ID] = BACKWARD_TOOL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_MELEE_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_FORWARD_DASH_ACTION_ID] = GROUND_FORWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_BACKWARD_DASH_ACTION_ID] = GROUND_BACKWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_ACTION_ID] = ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_ACTION_ID] = GROUND_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_SPECIAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UPWARD_SPECIAL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_HITSTUN_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][BACKWARD_MELEE_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UPWARD_MELEE_ACTION_ID] = UPWARD_MELEE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][DOWNWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ON_HIT_GROUND_GRAB_ACTION_ID] = ON_HIT_GROUND_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ON_HIT_AIR_SPECIAL_REKA1_HIT_MVM_STOP_ACTION_ID] = ON_HIT_AIR_SPECIAL_REKA1_HIT_MVM_STOP_MVM_ANIME_ID
		
	#animationLookup[MVM_ANIME_IX][ON_HIT_AIR_GRAB_ACTION_ID] = ON_HIT_AIR_GRAB_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][GROUND_IN_PLACE_TECH_ACTION_ID] = GROUND_IN_PLACE_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_BOUNCE_UP_TECH_ACTION_ID] = GROUND_TECH_BOUNCE_UP_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_UP_TECH_ACTION_ID] = WALL_TECH_BOUNCE_UP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_DOWN_TECH_ACTION_ID] = WALL_TECH_BOUNCE_DOWN_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_BOUNCE_AWAY_TECH_ACTION_ID] = WALL_TECH_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][ROLLING_BACKWARD_TECH_ACTION_ID] = TECH_ROLL_BACKWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ROLLING_FORWARD_TECH_ACTION_ID] = TECH_ROLL_FORWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_BOUNCE_BACK_TECH_ACTION_ID] = CEILING_BOUNCE_BACK_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_BOUNCE_FORWARD_TECH_ACTION_ID] = CEILING_BOUNCE_FORWARD_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_TECH_ACTION_ID] = AIR_TECH_IN_PLACE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CEILING_BOUNCE_DOWN_TECH_ACTION_ID] = CEILING_TECH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][WALL_TECH_ACTION_ID] = AIR_TECH_IN_PLACE_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][BUDGET_BLOCK_HIT_LAG_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BUDGET_BLOCK_HIT_LAG_ACTION_ID] = null
	#animationLookup[MVM_ANIME_IX][AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = AIR_BLOCK_STUN_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_STOP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CROUCHING_BUDGET_BLOCK_HIT_LAG_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][LEAVE_PLATFROM_HALT_ACTION_ID] = LEAVE_PLATFROM_HALT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][LAND_ON_PLATFROM_ACTION_ID] = LAND_ON_PLATFROM_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_HITSTUN_BREAK_FREE_ACTION_ID] = AIR_HITSTUN_BREAK_FREE_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][STOP_PLATFORM_LEAVE_MOMENTUM_ACTION_ID] = STOP_PLATFORM_LEAVE_MOMENTUM_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PLATFORM_DROP_ACTION_ID] = PLATFORM_DROP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PLATFORM_ANIMATION_CANCEL_ACTION_ID] = STOP_PLATFORM_LEAVE_MOMENTUM_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][UNCROUCH_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][ON_HIT_GROUND_GRAB_ACTION_ID] = ON_HIT_GROUND_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][ON_HIT_AIR_GRAB_ACTION_ID] = ON_HIT_AIR_GRAB_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = F_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GETTING_PUSH_BLOCKED_ACTION_ID] = PUSH_BLOCK_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_PUSH_BLOCKING_ACTION_ID] = NON_MVM_PUSH_BLOCKING_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_PUSH_BLOCKING_ACTION_ID] = NON_MVM_PUSH_BLOCKING_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][GROUND_PUSH_BLOCKING_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	#animationLookup[MVM_ANIME_IX][AIR_PUSH_BLOCKING_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_UP_THROW_ACTION_ID] = GROUND_GRAB_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_FORWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_FORWARD_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_DOWN_THROW_ACTION_ID] = GROUND_GRAB_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_BACKWARD_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_BACKWARD_UP_THROW_ACTION_ID] = GROUND_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][GROUND_GRAB_NEUTRAL_THROW_ACTION_ID] = GROUND_GRAB_NEUTRAL_THROW_MVM_ANIME_ID
	
	animationLookup[MVM_ANIME_IX][AIR_GRAB_UP_THROW_ACTION_ID] = AIR_GRAB_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_FORWARD_UP_THROW_ACTION_ID] = AIR_GRAB_FORWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_FORWARD_THROW_ACTION_ID] = AIR_GRAB_FORWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID] = AIR_GRAB_FORWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_DOWN_THROW_ACTION_ID] = AIR_GRAB_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_BACKWARD_THROW_ACTION_ID] = AIR_GRAB_BACKWARD_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID] = AIR_GRAB_BACKWARD_DOWN_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID] = AIR_GRAB_BACKWARD_UP_THROW_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][AIR_GRAB_NEUTRAL_THROW_ACTION_ID] = AIR_GRAB_NEUTRAL_THROW_MVM_ANIME_ID
	
	
	animationLookup[MVM_ANIME_IX][NO_BALL_GROUND_IDLE_ACTION_ID] = animationLookup[MVM_ANIME_IX][GROUND_IDLE_ACTION_ID]
	#animationLookup[MVM_ANIME_IX][NO_BALL_AIR_TOOL_ACTION_ID] = ZERO_AIR_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NO_BALL_AIR_TOOL_ACTION_ID] = null #the no ball air tool mvm slow is busted. just leave null for now
	animationLookup[MVM_ANIME_IX][NO_BALL_NEUTRAL_TOOL_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][NO_BALL_FORWARD_TOOL_ACTION_ID] = null
	animationLookup[MVM_ANIME_IX][NO_BALL_DOWNWARD_TOOL_ACTION_ID] = null 
	animationLookup[MVM_ANIME_IX][NO_BALL_BACKWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID 
	animationLookup[MVM_ANIME_IX][NO_BALL_UPWARD_TOOL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID 
	animationLookup[MVM_ANIME_IX][NO_BALL_BLOCK_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID 
	animationLookup[MVM_ANIME_IX][NO_BALL_AIR_AUTO_RIPOST_ACTION_ID] = null 
	animationLookup[MVM_ANIME_IX][NO_BALL_WALK_BACK_ACTION_ID] = animationLookup[MVM_ANIME_IX][GROUND_MOVE_BACKWARD_ACTION_ID]
	animationLookup[MVM_ANIME_IX][NO_BALL_WALK_FORWARD_ACTION_ID] =  animationLookup[MVM_ANIME_IX][GROUND_MOVE_FORWARD_ACTION_ID]
	
	
	animationLookup[MVM_ANIME_IX][NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID] = GROUND_FORWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID] = GROUND_BACKWARD_DASH_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][APEX_ONLY_FAST_FALL_ACTION_ID] = AIR_DASH_DOWNWARD_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID] = PROXIMITY_GUARD_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID] = AIR_BLOCK_STUN_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEW_AIR_SPECIAL_P1_ACTION_ID] = NEW_AIR_SPECIAL_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEW_AIR_SPECIAL_P2_ACTION_ID] = AIR_SPECIAL_P2_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEW_AIR_SPECIAL_P3_ACTION_ID] = AIR_SPECIAL_P3_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEW_AIR_SPECIAL_ON_HIT_P1_ACTION_ID] = NEW_AIR_SPECIAL_P1_ON_HIT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEW_AIR_SPECIAL_ON_HIT_P2_ACTION_ID] = NEW_AIR_SPECIAL_P2_ON_HIT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NEW_AIR_SPECIAL_ON_HIT_P3_ACTION_ID] = NEW_AIR_SPECIAL_P3_ON_HIT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][STUNNED_ACTION_ID] = STUNNED_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][PERFECT_MOMENTUM_STOP_BLOCK_ACTION_ID] = PERFECT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][REBOUND_CLASH_BREAK_ACTION_ID] = REBOUND_CLASH_BREAK_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][MOMENTUM_STOP_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][CORNER_HITTING_PUSH_AWAY_ACTION_ID] = CORNER_HITTING_PUSH_AWAY_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID] = B_GROUND_DASH_CANCEL_RECOVERY_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][BASIC_CROUCH_CANCEL_ACTION_ID] = MOMENTUM_STOP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][BREAK_FROM_HITSTUN_HALT_ACTION_ID] = BREAK_FROM_HITSTUN_HALT_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID] = JUMP_MVM_ANIME_ID
	animationLookup[MVM_ANIME_IX][NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID] = JUMP_FORWARD_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID] = JUMP_BACKWARD_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][INVULNERABLE_GUARD_BREAK_ACTION_ID] = INVULNERABLE_GUARD_BREAK_MVM_ANIME_ID	
	animationLookup[MVM_ANIME_IX][GRAB_CANCEL_MOMENTUM_STOP_ACTION_ID] = GRAB_CANCEL_MOMENTUM_STOP_MVM_ANIME_ID	
	
	animationLookup[MVM_ANIME_IX][GETTING_PUSH_BLOCKED_IN_NEUTRAL_ACTION_ID]=GETTING_PUSH_BLOCKED_IN_NEUTRAL_MVM_ANIME_ID
	
	#make a backup of the map of animations	
	for actionId in animationLookup[SPRITE_ANIME_IX].keys():
		animationLookupDefault[SPRITE_ANIME_IX][actionId]=animationLookup[SPRITE_ANIME_IX][actionId]
	for actionId in animationLookup[MVM_ANIME_IX].keys():
		animationLookupDefault[MVM_ANIME_IX][actionId]=animationLookup[MVM_ANIME_IX][actionId]
	
	pushBlockActionIdWhiteList.append(AIR_DASH_BACKWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_DASH_FORWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_DASH_DOWNWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(JUMP_FORWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(JUMP_BACKWARD_ACTION_ID)		
	pushBlockActionIdWhiteList.append(NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID)		
	pushBlockActionIdWhiteList.append(AIR_JUMP_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_JUMP_FORWARD_ACTION_ID)
	pushBlockActionIdWhiteList.append(AIR_JUMP_BACKWARD_ACTION_ID)		
	pushBlockActionIdWhiteList.append(GROUND_FORWARD_DASH_ACTION_ID)
	pushBlockActionIdWhiteList.append(GROUND_BACKWARD_DASH_ACTION_ID)		
	pushBlockActionIdWhiteList.append(NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID)
	pushBlockActionIdWhiteList.append(NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID)	
		
		
	#sprite aniamtion ids to keep track of frames durations, null value since only need key for lookup
	frameTrackingSpriteAnimationIdMap[BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[PUSH_BLOCK_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[STUNNED_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[LANDING_HITSTUN_SPRITE_ANIME_ID]=null
	frameTrackingSpriteAnimationIdMap[REBOUND_SPRITE_ANIME_ID]=null
	#populate the command lookup map
	#melees
	commandLookupMap[AIR_NEUTRAL_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_MELEE
	commandLookupMap[NEUTRAL_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_MELEE
	commandLookupMap[BACKWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_MELEE
	commandLookupMap[FORWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_MELEE
	commandLookupMap[DOWNWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_MELEE
	commandLookupMap[UPWARD_MELEE_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_MELEE
	#specials
	commandLookupMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[NEW_AIR_SPECIAL_P1_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[NEW_AIR_SPECIAL_P2_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL	
	commandLookupMap[NEW_AIR_SPECIAL_P3_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[NEUTRAL_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_SPECIAL
	commandLookupMap[BACKWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_SPECIAL
	commandLookupMap[FORWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_SPECIAL
	commandLookupMap[DOWNWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_SPECIAL
	commandLookupMap[UPWARD_SPECIAL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_SPECIAL
	
	
	
	#tools
	commandLookupMap[AIR_NEUTRAL_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_TOOL
	commandLookupMap[NEUTRAL_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_TOOL
	commandLookupMap[BACKWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_TOOL
	commandLookupMap[FORWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_FORWARD_TOOL
	commandLookupMap[DOWNWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_DOWNWARD_TOOL
	commandLookupMap[UPWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_TOOL
	commandLookupMap[NO_BALL_UPWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_UPWARD_TOOL
	commandLookupMap[NO_BALL_BACKWARD_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_TOOL
	commandLookupMap[NO_BALL_AIR_TOOL_ACTION_ID]=inputManagerResource.Command.CMD_NEUTRAL_TOOL
	


	
	
	#movement
	commandLookupMap[JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP
	commandLookupMap[JUMP_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_FORWARD
	commandLookupMap[JUMP_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_BACKWARD
	commandLookupMap[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP
	commandLookupMap[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_FORWARD
	commandLookupMap[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_BACKWARD
	
	commandLookupMap[AIR_MOVE_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_FORWARD
	commandLookupMap[AIR_MOVE_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_BACKWARD
	
	commandLookupMap[AIR_JUMP_ACTION_ID]=inputManagerResource.Command.CMD_JUMP
	commandLookupMap[AIR_JUMP_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_FORWARD
	commandLookupMap[AIR_JUMP_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_JUMP_BACKWARD
	commandLookupMap[GROUND_MOVE_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_FORWARD
	commandLookupMap[GROUND_MOVE_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_MOVE_BACKWARD
	commandLookupMap[AIR_DASH_FORWARD_ACTION_ID]=inputManagerResource.Command.CMD_DASH_FORWARD
	commandLookupMap[AIR_DASH_BACKWARD_ACTION_ID]=inputManagerResource.Command.CMD_DASH_BACKWARD
	commandLookupMap[GROUND_FORWARD_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_FORWARD
	commandLookupMap[GROUND_BACKWARD_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_BACKWARD
	commandLookupMap[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_FORWARD
	commandLookupMap[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]=inputManagerResource.Command.CMD_DASH_BACKWARD
	commandLookupMap[AIR_DASH_DOWNWARD_ACTION_ID]=inputManagerResource.Command.CMD_AIR_DASH_DOWNWARD
	commandLookupMap[APEX_ONLY_FAST_FALL_ACTION_ID]=inputManagerResource.Command.CMD_AIR_DASH_DOWNWARD
	
	
	#other
	commandLookupMap[CROUCH_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	commandLookupMap[UNCROUCH_ACTION_ID]=inputManagerResource.Command.CMD_STOP_CROUCH
	commandLookupMap[AUTO_RIPOST_ACTION_ID]=inputManagerResource.Command.CMD_AUTO_RIPOST
	commandLookupMap[AIR_AUTO_RIPOST_ACTION_ID]=inputManagerResource.Command.CMD_AUTO_RIPOST
	commandLookupMap[GROUND_GRAB_ACTION_ID]=inputManagerResource.Command.CMD_GRAB
	commandLookupMap[AIR_GRAB_ACTION_ID]=inputManagerResource.Command.CMD_GRAB
	commandLookupMap[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	commandLookupMap[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	commandLookupMap[BASIC_CROUCH_CANCEL_ACTION_ID]=inputManagerResource.Command.CMD_CROUCH
	
	#commands that can't be used for counter ripost
	#counterRipostCmdBlackListMap[inputManagerResource.Command.CMD_UPWARD_SPECIAL]=null  #null, since only key is used
	
	#commandLookupMap[PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID]=inputManagerResource.Command.CMD_BACKWARD_CROUCH	
	
	pushBlockSpriteAnimeIds.append(PUSH_BLOCK_SPRITE_ANIME_ID)
	
	techSpriteAnimeIds.append(BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(CEILING_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(FORWARD_ROLLING_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID)
	techSpriteAnimeIds.append(WALL_TECH_SPRITE_ANIME_ID)
	
	
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_IDLE_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[NEW_AIR_SPECIAL_P2_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[NEW_AIR_SPECIAL_P3_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_NEUTRAL_TOOL_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[NO_BALL_AIR_TOOL_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[NEUTRAL_AIR_MELEE_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[JUMP_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_JUMP_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[NON_GND_DASH_CANCELABLE_JUMP_SPRITE_ANIME_ID]=null			
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_DASH_SPRITE_ANIME_ID]=null
	#airBornSupportPreventAutoFacingSpriteAnimeIds[BACK_AIR_DASH_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_DASH_BACK_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[GROUND_GRAB_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AIR_GRAB_SPRITE_ANIME_ID]=null	
	airBornSupportPreventAutoFacingSpriteAnimeIds[AUTO_RIPOST_SPRITE_ANIME_ID]=null
	airBornSupportPreventAutoFacingSpriteAnimeIds[AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID]=null
	
	reversalSpriteAnimationIdMap[UPWARD_SPECIAL_SPRITE_ANIME_ID] = null#DP
	reversalSpriteAnimationIdMap[AUTO_RIPOST_SPRITE_ANIME_ID] = null #alpha counter
	
	reversableSpriteAnimationIdMap[HITSTUN_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[LANDING_HITSTUN_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[AIR_HITSTUN_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[REBOUND_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[CROUCHING_BUDGET_BLOCK_HIT_LAG_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[FORWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[CEILING_TECH_SPRITE_ANIME_ID]=null
	reversableSpriteAnimationIdMap[WALL_TECH_SPRITE_ANIME_ID]=null
	
	invincibilitySpriteAnimationIdMap[AUTO_RIPOST_ON_HIT_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[UPWARD_SPECIAL_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[RIPOST_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[WALL_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[CEILING_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[INVULNERABLE_GUARD_BREAK_SPRITE_ANIME_ID]=null	
	invincibilitySpriteAnimationIdMap[FORWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	invincibilitySpriteAnimationIdMap[BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	
	
	techSpriteAnimationIdsMap[GROUND_IN_PLACE_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[FORWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[BACKWARD_ROLLING_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[CEILING_TECH_SPRITE_ANIME_ID]=null
	techSpriteAnimationIdsMap[WALL_TECH_SPRITE_ANIME_ID]=null
	
	#populate map to lookup action names
	#USED for combo list in pause hud
	actionIdNameMap[AIR_NEUTRAL_MELEE_ACTION_ID]="Hat flick"
	actionIdNameMap[NEUTRAL_MELEE_ACTION_ID]="Glove Punch"
	actionIdNameMap[BACKWARD_MELEE_ACTION_ID]="Bat Swing - Single"
	actionIdNameMap[FORWARD_MELEE_ACTION_ID]="Toe Poke"
	actionIdNameMap[DOWNWARD_MELEE_ACTION_ID]="Crouching Glove Punch"
	actionIdNameMap[UPWARD_MELEE_ACTION_ID]="Bat Swing - Hopping Fly Ball"
	#specials
	actionIdNameMap[NEW_AIR_SPECIAL_P1_ACTION_ID]="Bat Swing - Upper-cut Fly Ball"
	actionIdNameMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]="Bat Swing - Upper-cut Fly Ball"
	actionIdNameMap[NEW_AIR_SPECIAL_P2_ACTION_ID]="Bat Swing - Line Drive"
	actionIdNameMap[NEW_AIR_SPECIAL_P3_ACTION_ID]="Bat Swing - Ball Spike"
	actionIdNameMap[NEUTRAL_SPECIAL_ACTION_ID]="Bat Swing - Homerun"
	actionIdNameMap[BACKWARD_SPECIAL_ACTION_ID]="Bat Swing - Bunt"
	actionIdNameMap[FORWARD_SPECIAL_ACTION_ID]="Advancing Kick"
	actionIdNameMap[DOWNWARD_SPECIAL_ACTION_ID]="Bat Swing - Ground Ball"
	actionIdNameMap[UPWARD_SPECIAL_ACTION_ID]="Helmet Smasher"
	
	
	#tools
	actionIdNameMap[AIR_NEUTRAL_TOOL_ACTION_ID]="Ball Helix"
	actionIdNameMap[NEUTRAL_TOOL_ACTION_ID]="Fastball Fakeout"
	actionIdNameMap[BACKWARD_TOOL_ACTION_ID]="Highball Fakeout"
	actionIdNameMap[FORWARD_TOOL_ACTION_ID]="Fastball"
	actionIdNameMap[DOWNWARD_TOOL_ACTION_ID]="Lowball"
	actionIdNameMap[UPWARD_TOOL_ACTION_ID]="Highball"
	actionIdNameMap[NO_BALL_UPWARD_TOOL_ACTION_ID]="Quick Flick"
	actionIdNameMap[NO_BALL_BACKWARD_TOOL_ACTION_ID]="Pull-back"
	actionIdNameMap[NO_BALL_AIR_TOOL_ACTION_ID]="Helix Catch Pitch"
	
	
	
	#movement
	actionIdNameMap[JUMP_ACTION_ID]="Jump"
	actionIdNameMap[JUMP_FORWARD_ACTION_ID]="Forward Jump"
	actionIdNameMap[JUMP_BACKWARD_ACTION_ID]="Back Jump"
	
	actionIdNameMap[AIR_MOVE_FORWARD_ACTION_ID]="Move forward"
	actionIdNameMap[AIR_MOVE_BACKWARD_ACTION_ID]="Move backward"
	
	actionIdNameMap[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID]="Jump"
	actionIdNameMap[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID]="Forward Jump"
	actionIdNameMap[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID]="Back Jump"
	
	actionIdNameMap[AIR_JUMP_ACTION_ID]="Air Jump"
	actionIdNameMap[AIR_JUMP_FORWARD_ACTION_ID]="Air Forward Jump"
	actionIdNameMap[AIR_JUMP_BACKWARD_ACTION_ID]="Air Back Jump"
	
	actionIdNameMap[AIR_DASH_FORWARD_ACTION_ID]="Air Forward Dash"
	actionIdNameMap[AIR_DASH_BACKWARD_ACTION_ID]="Air Back Dash"
	actionIdNameMap[GROUND_FORWARD_DASH_ACTION_ID]="Ground Forward Dash"
	actionIdNameMap[GROUND_BACKWARD_DASH_ACTION_ID]="Ground Back Dash"
	actionIdNameMap[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]="Ground Forward Dash"
	actionIdNameMap[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]="Ground Back Dash"
	actionIdNameMap[AIR_DASH_DOWNWARD_ACTION_ID]="Instant Fast Fall"
	actionIdNameMap[APEX_ONLY_FAST_FALL_ACTION_ID]="Fast Fall"
	actionIdNameMap[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]="Crouch Cancel"
	actionIdNameMap[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]="Crouch Cancel"	
	actionIdNameMap[BASIC_CROUCH_CANCEL_ACTION_ID]="Crouch Cancel"	
	actionIdNameMap[CROUCH_ACTION_ID]="Crouch"
	actionIdNameMap[AUTO_RIPOST_ACTION_ID]="Auto Ripost"
	actionIdNameMap[AIR_AUTO_RIPOST_ACTION_ID]="Air Auto Ripost"
	actionIdNameMap[GROUND_GRAB_ACTION_ID]="Grab"
	actionIdNameMap[AIR_GRAB_ACTION_ID]="Grab"




	
	#description of moves
	actionIdDetailsMap[AIR_NEUTRAL_MELEE_ACTION_ID]="Quick light hat flick sending opponent slightly up and in front."
	actionIdDetailsMap[NEUTRAL_MELEE_ACTION_ID]="Quick light punch that keeps opponent in place"
	actionIdDetailsMap[BACKWARD_MELEE_ACTION_ID]="Quick short/medium reaching light bat swing that sends opponents flying back slowly and horizontally. \n\n Baseball bat hit: the ball is sent horizontally at a slight upwards angle."
	actionIdDetailsMap[FORWARD_MELEE_ACTION_ID]="Glove leans back and lowers himself to the ground to do a quick short/medium low reaching kick"
	actionIdDetailsMap[DOWNWARD_MELEE_ACTION_ID]="Crouching quick light punch that knocks the opponent very slighty upwards and away"
	actionIdDetailsMap[UPWARD_MELEE_ACTION_ID]="Medium/long reach bat anti-air attack. Glove takes his bat out and hops upward while poking upwards with his bat, knocking opponents slowly upward, setting up for easy air juggles. Glove is on the ground for a portion of the active part of this animation, so ground auto-cancels on-hit are possible. \n\n Baseball bat hit: the ball is sent vertically up with low gravity and slowly moves foward, making a high arching ball trajectory."
	#specials
	actionIdDetailsMap[NEW_AIR_SPECIAL_P1_ACTION_ID]="Short/medium reach bat attack. Glove swings his bat in the air in an upper-cut motion from down to upward. There are 3 parts to the hitbox (low, medium, and upper), each knocking back the opponent at slightly different angles. The duration of the hitstun also varies, having the tip (upper) of the bat have the most hitstun. The timing of the next part of the Air-Special reka combo depends on which part of the bat hit. \n\n Baseball bat hit: the ball is sent vertically up at a 90 degree angle and flies outside the screen temporarily and the ball is active the entire time in the air."
	actionIdDetailsMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=actionIdDetailsMap[NEW_AIR_SPECIAL_P1_ACTION_ID]
	actionIdDetailsMap[NEW_AIR_SPECIAL_P2_ACTION_ID]="Short/medium reach bat attack. Glove swings his bat horizontally like a sword. It sends the opponent flying horizontally. Hitting with this will make it difficult to hit the opponent with the 3rd part of the Air Special unless in a corner. Generally whiffing this attack will enable comboing into the 3rd part. \n\n Baseball bat hit: the ball is sent flying fast and horiontally"
	actionIdDetailsMap[NEW_AIR_SPECIAL_P3_ACTION_ID]="Short/medium reach bat attack. Glove puts his bat over his head and swings downward, sending the opponent flying directly downward and into the floor. When the opponent hits the floor they bounce up for a fixed duration, enable an air combo (or ground, with a fast fall) to continue. \n\n Baseball bat hit: the ball is sent flying directly downward"
	actionIdDetailsMap[NEUTRAL_SPECIAL_ACTION_ID]="Short/medium reach bat attack. Gloves swings his bat in a standard fasion, sending the opponent flying at an upward angle and is good to setup a juggle. \n\n Baseball bat hit: the ball is sent flying at a 45 degrees angle away"
	actionIdDetailsMap[BACKWARD_SPECIAL_ACTION_ID]="Medium/long reach bat attack. Glove extends his bat out momentarily and then spins around, sending the opponent slowly flying away horizontally. Glove is on the ground for a portion of the active part of this animation, so ground auto-cancels on-hit are possible. \n\n Baseball bat hit: the ball is sent slowly flying away horizontally."
	actionIdDetailsMap[FORWARD_SPECIAL_ACTION_ID]="A long startup short-hop advancing kick that deals a lot of guard pressure. This attack can be avoided by using appropriate spacing and crouching under it"
	actionIdDetailsMap[DOWNWARD_SPECIAL_ACTION_ID]="Short/medium reach bat attack. Glove swings his bat low to the ground. There is very little knockbakc, and the opponent generally stays in place"
	actionIdDetailsMap[UPWARD_SPECIAL_ACTION_ID]="medium range quick heavy anti-air invincible instant reversal. It has large recovery and is punishable on block. Sends the opponent flying accross the screen to bounce off the walls/ceilings and then knocks them down near you."
	
	
	#tools
	actionIdDetailsMap[AIR_NEUTRAL_TOOL_ACTION_ID]="A medium ball-string attack. Glove stops his air momentum and hops up, spinning his ball on its string in a 360 degree motion. The tip of the string, the ball, is the sweet-spot hitbox of this attack. At the end of the animation Glove throws the ball down at a 45 degree angle."
	actionIdDetailsMap[NEUTRAL_TOOL_ACTION_ID]="A slow short range ball-string attack. Glove does a ball throw fakeout and instead of throwing the ball he keeps it nearby in front of him and tethers it to his string. \n\nNo-ball: without the ball in hand, this aniamtion does nothing."
	actionIdDetailsMap[BACKWARD_TOOL_ACTION_ID]="A slow medium range ball-string anti-air attack. Glove does a ball throw fakeout and instead of throwing the ball upward he keeps it nearby up and in front of him and tethers it to his string"
	actionIdDetailsMap[FORWARD_TOOL_ACTION_ID]="Glove pitches his ball horizontally accross the screen. \n\nNo-ball: without the ball in hand, this aniamtion does nothing."
	actionIdDetailsMap[DOWNWARD_TOOL_ACTION_ID]="Glove under-hand pitches his ball horizontally low accross the screen and the ball bounces on the ground. Knocks the player to the ground. \n\nNo-ball: without the ball in hand, this aniamtion does nothing."
	actionIdDetailsMap[UPWARD_TOOL_ACTION_ID]="Glove pitches his ball over head and keeps the ball in the air in front of him"
	actionIdDetailsMap[NO_BALL_UPWARD_TOOL_ACTION_ID]="Glove attempts to interrupt the ball's current animation using his string and flicks the ball upward a short distance before."
	actionIdDetailsMap[NO_BALL_BACKWARD_TOOL_ACTION_ID]="Glove attempts to interrupt the ball's current animation using his string and pulls the ball back to him. The ball will keep travelling to where Glove initially pulled the ball and if Glove doesn't catch it, it will eventually bounce of the walls/ceiling/floor and remain active for a decent amount of time"
	actionIdDetailsMap[NO_BALL_AIR_TOOL_ACTION_ID]="Glove attempts to interrupt the ball's current animation using his string and pulls the ball back to him. Glove also attacks with his gloves. The ball will keep travelling to where Glove initially pulled the ball and if Glove doesn't catch it, it will eventually bounce of the walls/ceiling/floor and remain active for a decent amount of time. If Glove catches it in time, he will throw the ball."
	
	
	airActionIdMap[AIR_AUTO_RIPOST_ACTION_ID]=null
	airActionIdMap[AIR_AUTO_RIPOST_ON_HIT_ACTION_ID]=null
	airActionIdMap[AIR_BUDGET_BLOCK_HIT_LAG_ACTION_ID]=null
	airActionIdMap[AIR_DASH_BACKWARD_ACTION_ID]=null
	airActionIdMap[AIR_DASH_FORWARD_ACTION_ID]=null
	airActionIdMap[AIR_DASH_DOWNWARD_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_BACKWARD_DOWN_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_BACKWARD_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_BACKWARD_UP_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_NEUTRAL_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_DOWN_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_FORWARD_DOWN_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_FORWARD_THROW_ACTION_ID]=null
	airActionIdMap[AIR_GRAB_FORWARD_UP_THROW_ACTION_ID]=null
	airActionIdMap[AIR_HITSTUN_ACTION_ID]=null
	airActionIdMap[AIR_HITSTUN_BREAK_FREE_ACTION_ID]=null
	airActionIdMap[AIR_IDLE_ACTION_ID]=null
	airActionIdMap[AIR_JUMP_ACTION_ID]=null
	airActionIdMap[AIR_JUMP_BACKWARD_ACTION_ID]=null
	airActionIdMap[AIR_JUMP_FORWARD_ACTION_ID]=null
	airActionIdMap[AIR_MOVE_BACKWARD_ACTION_ID]=null
	airActionIdMap[AIR_MOVE_FORWARD_ACTION_ID]=null
	airActionIdMap[AIR_MOVE_STOP_ACTION_ID]=null
	airActionIdMap[AIR_NEUTRAL_MELEE_ACTION_ID]=null
	airActionIdMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=null
	airActionIdMap[AIR_NEUTRAL_TOOL_ACTION_ID]=null
	airActionIdMap[AIR_RIPOST_ACTION_ID]=null
	airActionIdMap[NO_BALL_AIR_TOOL_ACTION_ID]=null
	airActionIdMap[NEW_AIR_SPECIAL_P1_ACTION_ID]=null
	airActionIdMap[NEW_AIR_SPECIAL_P2_ACTION_ID]=null
	airActionIdMap[NEW_AIR_SPECIAL_P3_ACTION_ID]=null
	
	
	autoCancelMaskMap[JUMP_ACTION_ID]=1 #bitshift 0
	autoCancelMaskMap[JUMP_FORWARD_ACTION_ID]=1 << 1 #2
	autoCancelMaskMap[JUMP_BACKWARD_ACTION_ID]=1 << 2#4
	autoCancelMaskMap[GROUND_IDLE_ACTION_ID]=1 << 3 #8
	autoCancelMaskMap[SLIDING_GROUND_IDLE_ACTION_ID]=1 << 3 #SAME AS ground idle	
	autoCancelMaskMap[GROUND_MOVE_FORWARD_ACTION_ID]=1 << 4 #16
	autoCancelMaskMap[GROUND_MOVE_BACKWARD_ACTION_ID]=1 << 5 #32...
	autoCancelMaskMap[CROUCH_ACTION_ID]=1 << 6
	autoCancelMaskMap[NEUTRAL_MELEE_ACTION_ID]=1 << 7
	autoCancelMaskMap[NEUTRAL_SPECIAL_ACTION_ID]=1 << 8
	autoCancelMaskMap[NEUTRAL_TOOL_ACTION_ID]=1 << 9
	autoCancelMaskMap[BACKWARD_SPECIAL_ACTION_ID] = 1 << 10
	autoCancelMaskMap[AUTO_RIPOST_ACTION_ID]=1 << 11
	
	autoCancelMaskMap[AIR_IDLE_ACTION_ID]=1 << 12
	autoCancelMaskMap[AIR_MOVE_FORWARD_ACTION_ID]=1 << 13
	autoCancelMaskMap[AIR_MOVE_BACKWARD_ACTION_ID]=1 << 14
	autoCancelMaskMap[AIR_DASH_FORWARD_ACTION_ID]=1 << 15
	autoCancelMaskMap[AIR_DASH_BACKWARD_ACTION_ID]=1 << 16
	autoCancelMaskMap[AIR_NEUTRAL_MELEE_ACTION_ID]=1 << 17
	autoCancelMaskMap[AIR_NEUTRAL_SPECIAL_ACTION_ID]=1 << 18
	autoCancelMaskMap[AIR_NEUTRAL_TOOL_ACTION_ID]=1 << 19
	autoCancelMaskMap[AIR_DASH_DOWNWARD_ACTION_ID]=1 << 20
	autoCancelMaskMap[AIR_MOVE_STOP_ACTION_ID] = 1 << 21
	autoCancelMaskMap[AIR_AUTO_RIPOST_ACTION_ID]=1 << 22
	autoCancelMaskMap[FORWARD_SPECIAL_ACTION_ID]=1 << 23
	autoCancelMaskMap[DOWNWARD_MELEE_ACTION_ID]=1 << 24
	autoCancelMaskMap[UPWARD_TOOL_ACTION_ID]=1 << 25
	autoCancelMaskMap[DOWNWARD_TOOL_ACTION_ID]=1 << 26
	autoCancelMaskMap[FORWARD_TOOL_ACTION_ID]=1 << 27
	autoCancelMaskMap[BACKWARD_TOOL_ACTION_ID]=1 << 28
	autoCancelMaskMap[UPWARD_SPECIAL_ACTION_ID]=1 << 29
	autoCancelMaskMap[FORWARD_MELEE_ACTION_ID]=1 << 30
	autoCancelMaskMap[BACKWARD_SPECIAL_ACTION_ID]=1 << 31
	
	autoCancelMaskMap2[DOWNWARD_SPECIAL_ACTION_ID]=1 #bitshift 0
	autoCancelMaskMap2[BACKWARD_MELEE_ACTION_ID]=1 << 1
	autoCancelMaskMap2[UPWARD_MELEE_ACTION_ID]=1 << 2
	autoCancelMaskMap2[GROUND_FORWARD_DASH_ACTION_ID]=1 << 3
	autoCancelMaskMap2[GROUND_BACKWARD_DASH_ACTION_ID]=1 <<4
	autoCancelMaskMap2[AIR_GRAB_ACTION_ID]=1 <<5
	autoCancelMaskMap2[GROUND_GRAB_ACTION_ID]=1 <<6
	autoCancelMaskMap2[PROXIMITY_GUARD_CROUCHING_HOLD_BACK_BLOCK_ACTION_ID]=1 <<7
	autoCancelMaskMap2[PLATFORM_DROP_ACTION_ID]=1 <<8
	autoCancelMaskMap2[PLATFORM_ANIMATION_CANCEL_ACTION_ID]=1 <<9
	autoCancelMaskMap2[FORWARD_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=1 <<10
	autoCancelMaskMap2[NON_CROUCH_CANCELABLED_F_GROUND_DASH_ACTION_ID]=1 <<11
	autoCancelMaskMap2[NON_CROUCH_CANCELABLED_B_GROUND_DASH_ACTION_ID]=1 <<12
	autoCancelMaskMap2[APEX_ONLY_FAST_FALL_ACTION_ID]=1 <<13
	autoCancelMaskMap2[PROXIMITY_GUARD_STANDING_HOLD_BACK_BLOCK_ACTION_ID]=1 <<14
	autoCancelMaskMap2[PROXIMITY_GUARD_AIR_HOLD_BACK_BLOCK_ACTION_ID]=1 <<15
	autoCancelMaskMap2[GROUND_PUSH_BLOCKING_ACTION_ID]=1 <<16 
	autoCancelMaskMap2[AIR_PUSH_BLOCKING_ACTION_ID]=1 <<17
	autoCancelMaskMap2[AIR_JUMP_ACTION_ID]=1 << 18
	autoCancelMaskMap2[AIR_JUMP_FORWARD_ACTION_ID]=1 << 19
	autoCancelMaskMap2[AIR_JUMP_BACKWARD_ACTION_ID]=1 << 20
	autoCancelMaskMap2[BACK_GROUND_DASH_CANCEL_RECOVERY_ACTION_ID]=1 << 21
	autoCancelMaskMap2[BASIC_CROUCH_CANCEL_ACTION_ID]=1 << 22
	autoCancelMaskMap2[NON_GND_DASH_CANCELABLE_JUMP_ACTION_ID] = 1 << 23
	autoCancelMaskMap2[NON_GND_DASH_CANCELABLE_F_JUMP_ACTION_ID] = 1 << 24
	autoCancelMaskMap2[NON_GND_DASH_CANCELABLE_B_JUMP_ACTION_ID] = 1 << 25
	
	
	
	customSpamProrationAttackMap[UPWARD_SPECIAL_SPRITE_ANIME_ID]=[	
	[1,0.65,0.35,0.15,0.05],
	null,#[0,0,-1,-1,-5,-5,],
	null,#[0.95,0.95,0.9,0.9,0.85,0.85,], 
	]
	
	#delayed tap action series
	delayedTapActionIdLookup[AIR_NEUTRAL_SPECIAL_ACTION_ID]=NEW_AIR_SPECIAL_P1_ACTION_ID
	delayedTapActionIdLookup[NEW_AIR_SPECIAL_P1_ACTION_ID]=NEW_AIR_SPECIAL_P2_ACTION_ID
	delayedTapActionIdLookup[NEW_AIR_SPECIAL_P2_ACTION_ID]=NEW_AIR_SPECIAL_P3_ACTION_ID
	
	delayedTapActionIdReverseLookup[NEW_AIR_SPECIAL_P3_ACTION_ID]=NEW_AIR_SPECIAL_P2_ACTION_ID
	delayedTapActionIdReverseLookup[NEW_AIR_SPECIAL_P2_ACTION_ID]=NEW_AIR_SPECIAL_P1_ACTION_ID
	delayedTapActionIdReverseLookup[NEW_AIR_SPECIAL_P1_ACTION_ID]=AIR_NEUTRAL_SPECIAL_ACTION_ID
	
	#iterate all actions
	var i = 0
	while i <= LARGEST_ACTION_ID:
		
		#by default actions are the same regardless
		#of if glove has ball of not
		var actionPairRow = []
		actionPairRow.append(i)
		actionPairRow.append(i)
		
		#add the id pair row
		actionIdGroups.append(actionPairRow)
		i = i +1
	
	#now here we explicilty state which animation is dependent on 
	#if glove has ball or not
	
	actionIdGroups[GROUND_IDLE_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_GROUND_IDLE_ACTION_ID
	actionIdGroups[AIR_NEUTRAL_TOOL_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_AIR_TOOL_ACTION_ID
	actionIdGroups[NEUTRAL_TOOL_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_NEUTRAL_TOOL_ACTION_ID
	actionIdGroups[FORWARD_TOOL_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_FORWARD_TOOL_ACTION_ID
	actionIdGroups[DOWNWARD_TOOL_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_DOWNWARD_TOOL_ACTION_ID
	actionIdGroups[BACKWARD_TOOL_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_BACKWARD_TOOL_ACTION_ID
	actionIdGroups[UPWARD_TOOL_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_UPWARD_TOOL_ACTION_ID
	actionIdGroups[AUTO_RIPOST_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_BLOCK_ACTION_ID
	actionIdGroups[AIR_AUTO_RIPOST_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_AIR_AUTO_RIPOST_ACTION_ID
	
	
	actionIdGroups[GROUND_MOVE_FORWARD_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_WALK_FORWARD_ACTION_ID
	actionIdGroups[GROUND_MOVE_BACKWARD_ACTION_ID][NO_BALL_ANIMATIONS_IX]=NO_BALL_WALK_BACK_ACTION_ID
	
	
	#attackId = attackId+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	#gloveBallActionAnimeManagerResource
	
	
	customSpamProrationAttackMap[NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID]=[
	#[1,1,1,0.55,0.35,0.15,0.05], #WE want first 3 hits of reka to not have proration, since it's a 3 hit combo when in corner
	 #[1,0.3,0.1], #default hitstun proration
	[1,1,1,0.55,0.35,0.15,0.05],#meaty
	[0,0,0,-20,-25,-45,-60],#basic hitstunproration	
	[0.95,0.8,0.55,0.4,0.35,0.25,0.15,0.05] #make air special reka spamming not do too much damage
	]
	
			
	customSpamProrationAttackMap[NEUTRAL_MELEE_SPRITE_ANIME_ID]=[
	null,
	[0,-1,-2,-3,-10,-15],
	[1,1,1]#NO PRORATION on damage spam
	]
	
	customSpamProrationAttackMap[BACKWARD_TOOL_SPRITE_ANIME_ID]=[
	[1,0.5,0.35,0.15,0.05],#meaty
	null,
	null, #default damage proration
	]
	
	
	customSpamProrationAttackMap[BACK_MELEE_SPRITE_ANIME_ID]=[
	null,
	[0,-1,-2,-3,-10,-15],
	[1,1,1]#NO PRORATION on damage spam
	]
	
	customSpamProrationAttackMap[FORWARD_MELEE_SPRITE_ANIME_ID]=[
	[1,0.65,0.5],
	[0,-1,-5,-15],
	null,#default damage proration
	]
	customSpamProrationAttackMap[DOWN_WARD_MELEE_SPRITE_ANIME_ID]=[
	 [1,0.9,0.5,0.35], #default hitstun proration
	[0,-1,-3,-15],
	null, #default damage proration
	]


	#here we specify that the melees are all the same for spam hitstun prorations reasons
	spamHitstunProrationSpriteAnimeIdRemap[AIR_NEUTRAL_SPECIAL_SPRITE_ANIME_ID]=NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID
	spamHitstunProrationSpriteAnimeIdRemap[NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID]=NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID
	spamHitstunProrationSpriteAnimeIdRemap[NEW_AIR_SPECIAL_P2_SPRITE_ANIME_ID]=NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID
	spamHitstunProrationSpriteAnimeIdRemap[NEW_AIR_SPECIAL_P3_SPRITE_ANIME_ID]=NEW_AIR_SPECIAL_P1_SPRITE_ANIME_ID

	#the proration for the base ball bat hits
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_P2_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_P3_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	
	#make sure all the no string ball+bat hits are same as with string
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_D_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.D_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_NEW_B_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.NEW_B_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_U_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.U_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_F_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.F_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_N_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.N_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_B_MELEE_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.B_MELEE_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_U_MELEE_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.U_MELEE_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_AIR_SPECIAL_P1_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_AIR_SPECIAL_P2_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	spamHitstunProrationSpriteAnimeIdRemap[gloveBallActionAnimeManagerResource.NO_STRING_AIR_SPECIAL_P3_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET
	
	
	var ballAndBatHitProrationTriples=[
	 null, #default hitstun proration
	null,
	[1,0.05,0.05,0.05,0.05] #100% hit damage, but next time ball + bat hits 2nd time, do like no daamge
	]
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.U_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.F_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.N_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.B_MELEE_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.U_MELEE_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.AIR_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.D_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	customSpamProrationAttackMap[gloveBallActionAnimeManagerResource.NEW_B_SPECIAL_BAT_HIT_SPRITE_ANIME_ID+GLOBALS.PROJECTILE_SPRITE_ANIME_ID_PRORATION_TRACKING_OFFSET]=ballAndBatHitProrationTriples
	
	
#const  = 51
#const NO_BALL_NEUTRAL_TOOL_ACTION_ID = 52
#const NO_BALL_FORWARD_TOOL_ACTION_ID = 53
#const NO_BALL_DOWNWARD_TOOL_ACTION_ID = 54
#const NO_BALL_BACKWARD_TOOL_ACTION_ID = 55
#const NO_BALL_UPWARD_TOOL_ACTION_ID = 56
#const NO_BALL_BLOCK_ACTION_ID = 57
	#end ready
	
	
	
func populateCommandAttackMap(inputManager):
	
	#note, make sure the map is consistent with map defined in ready()
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_NEUTRAL_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_DOWNWARD_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_FORWARD_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_BACKWARD_MELEE] = true
	cmdAttackMaps[MELEE_IX][inputManager.Command.CMD_UPWARD_MELEE] = true
	
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_NEUTRAL_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_BACKWARD_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_FORWARD_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_DOWNWARD_SPECIAL] = true
	cmdAttackMaps[SPECIAL_IX][inputManager.Command.CMD_UPWARD_SPECIAL] = true
	
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_NEUTRAL_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_UPWARD_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_DOWNWARD_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_BACKWARD_TOOL] = true
	cmdAttackMaps[TOOL_IX][inputManager.Command.CMD_FORWARD_TOOL] = true


#toggle the action id group index based on if hase ball	
func setHasBallFlag(flag):
	if flag:
		currentActionIdGroup = WITH_BALL_ANIMATIONS_IX
	else:
		currentActionIdGroup = NO_BALL_ANIMATIONS_IX



	
#sub classes can override this to change the aciton id dynamically
#depending on some special state. This function will be called when resolving the
#sprite id and movement id
func actionIdRemapHook(actionId): 
	return _actionIdRemapHook(actionId,currentActionIdGroup)
	
func _actionIdRemapHook(actionId,stanceIx):
	if actionId == null:
		return null
	return actionIdGroups[actionId][stanceIx]
	
func init(playerController):
	.init(playerController)
	
	#set the node paths to dash basic movements so sped can be adjusted
	#forwardAirDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/air-dash-forward/cplx_mvm0/bm0"
	#backwardAirDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/air-dash-backward/cplx_mvm0/bm0"
	#forwardGroundDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/ground-dash-forward/cplx_mvm0/bm0"
	#backwardGroundDashBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/ground-dash-backward/cplx_mvm0/bm0"	
	
	#forwardJumpBM1NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-forward/cplx_mvm0/bm0"
	#backwardJumpBM1NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-backward/cplx_mvm0/bm0"
	#forwardJumpBM2NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-forward/cplx_mvm1/bm0"
	#backwardJumpBM2NodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump-backward/cplx_mvm1/bm0"
	#neutralJumpBMNodePath = "PlayerController/ActionAnimationManager/MovementAnimationManager/MovementAnimations/jump/cplx_mvm0/bm0"
	
func reset():
	.reset()
	currentActionIdGroup = WITH_BALL_ANIMATIONS_IX